### ISSUE TITLE
ccache, [options] before compiler

### ISSUE THREAD

**Issue by fekir** [ccache/ccache#1306] opened 2023-06-30 13:40 UTC
Currently ccache can be invoked in one of the following way

```
ccache [options]
ccache compiler [compiler options]
compiler [compiler options]            (ccache masquerading as the compiler)
```

Has it ever been considered supporting

```
ccache [options] -- compiler [compiler options]
```

?

It would make it easier to use, for example `ccache` with CMake if someone want to use different cache directories (depending, for example, on the project/branch/...)

```
set(CMAKE_C_COMPILER_LAUNCHER "ccache;-d;${CCACHE_FOLDER};--" CACHE STRING "Compiler launcher for C")
```

and it generally reduces the need to define environment variables (which might be more complicated than setting a parameter in a build system)

**Comment by jrosdahl** [comment] 2023-07-01 08:09
This was suggested in #1035 and added in a different form (to allow setting any configuration, not just the cache directory) in ccache 4.8:

```
ccache [KEY=VALUE …​] compiler [compiler options]
```

Such command line settings have the highest priority. See [_Configuration_](https://ccache.dev/manual/4.8.2.html#_configuration) in the manual for details.

Example:

```
ccache cache_dir=${CCACHE_FOLDER} compiler -c ...
```

**Comment by jrosdahl** [comment] 2023-07-01 08:10
Duplicate of #1035

**Closed by jrosdahl** 2023-07-01 08:10 UTC
Labels: feature
