### ISSUE TITLE
Cache file size mismatch on NTFS

### ISSUE THREAD

**Issue by nkr0** [ccache/ccache#1354] opened 2023-11-14 19:45 UTC
This is quite similar to issue #1332 except that the file system in this case is NTFS.

### How to reproduce ###
Install ccache and compile on windows with NTFS file system. `ccache -sx` should show roughly the same value for `Cache size` and `Total data` and cleanup when `Cache size` exceeds limit.

### Actual behavior ###
Unlike #1332 , `Cache size` shows a non-zero value. But still much less than `Total data`. Checking properties of the folder, `Total data` seems to be more accurate. Cache is not cleaned because `Cache size` is less than max limit.
<img width="270" alt="ccache-windows" src="https://github.com/ccache/ccache/assets/42086312/5c279eba-c9e3-47cc-9e1c-28540425abbc">

### Expected behavior ###
Both values match on linux and cleanup keeps cache size under limit.
<img width="223" alt="ccache-linux" src="https://github.com/ccache/ccache/assets/42086312/66cbfb88-7ced-4654-8506-cdf9194252fc">

### Environment ###
ccache version 4.8.3 with msvc 2019 on windows
ccache version 4.5.1 with gcc 11 on linux

**Comment by jrosdahl** [comment] 2024-11-10 08:06
I cannot reproduce this.

@nkr0:

1. Is this still a problem with latest ccache?
2. Is this with the prebuilt ccache binary from https://ccache.dev/download.html or a custom binary?
3. Have you enabled NTFS transparent compression on the volume or folder where the cache is located?
4. Does _Cache size_ correct itself when you run `ccache -c`?

**Comment by nkr0** [comment] 2024-11-10 10:02
1. I had noticed this problem on our build VMs. Interestingly enough, I'm also unable to reproduce this with the same ccache 4.8.3. I'm not really sure what all changed over the year. A much bigger cache from a year of builds ~12GB. OS updates for sure. We also migrated from VS 2019 to 2022.
2. Yes.
3. No.

**Comment by jrosdahl** [comment] 2024-11-10 13:39
Thanks, then I'll close the issue for now. Feel free to comment if you experience the problem again.

**Closed by jrosdahl** 2024-11-10 13:39 UTC
Labels: bug, os: windows, help wanted
