### ISSUE TITLE
failed to link error with Docker Hyper-V isolation on windows

### ISSUE THREAD

**Issue by asergunov** [ccache/ccache#1185] opened 2022-10-18 16:58 UTC
We have gitlab-runner with docker-windows executor. That means it builds using the windows-based Docker images.

Docker on windows supports two level of isolation for windows containers: --isolation=process and --isolation=hyperv.

The first one is using the same core as the current windows version so it could run only the images supported by current kernel. Hyper-V is creates separate kernel for each container so it could run any windows version but slower then process one. 

All works fine in process isolation but in hyper-v isolation ccache gives us error:
```
ccache: error: failed to link C:\ccache-primary-storage/tmp/tmp.cpp_stdout.FT8nV1 to C:\ccache-primary-storage/tmp/tmp.cpp_stdout.FT8nV1.ii: The request is not supported.
```
The C:\ccache-primary-storage is mapped to host machine folder so runners can share caches.

Container is based on mcr.microsoft.com/windows:2004

Any advice?

**Comment by jrosdahl** [comment] 2022-10-18 18:47
Hi there,

You forgot to mention which ccache version you're using. From your description, it sounds like a duplicate of #1079 which was fixed in ccache 4.6.2.

(Also: Next time, please select _Bug report_ when creating a bug report. Then you get instructions on what information to provide.)

**Comment by asergunov** [comment] 2022-10-19 05:13
Right. It's 4.6.1 Let me try 4.6.2
```
ccache --version
ccache version 4.6.1
Features: file-storage http-storage redis-storage

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2022 Joel Rosdahl and other contributors

See <https://ccache.dev/credits.html> for a complete list of contributors.   

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later   
version.```

**Comment by jrosdahl** [comment] 2022-10-22 18:16
@asergunov: Did it work out?

**Comment by asergunov** [comment] 2022-10-24 07:49
I hope to check this week.

вс, 23 окт. 2022 г. в 00:16, Joel Rosdahl ***@***.***>:

**Closed** 2022-12-23 15:00 UTC
Labels: bug, awaiting feedback, os: windows
