### ISSUE TITLE
less cacheable calls/hit when compiling the kernel with ccache

### ISSUE THREAD

**Issue by ptr1337** [ccache/ccache#1207] opened 2022-11-02 20:30 UTC
### How to reproduce ###

1. Install ccache
2. Compile kernel with ccache enabled
3. Check the ccache stats

### Actual behavior ###

Earlier I have compiled the kernel without debug enabled and ccache did hit very well, noticeable compile speed improvement.
Since like a month, I did enabled CONFIG_DEBUG at the kernel again, started to use ccache and I noticed there are nearly no hits.
I tried to set different sloppiness options,...

I cleared the cache, enabled ccache and the following stats are after the first build:
```
Cacheable calls:      84 / 22505 ( 0.37%)
  Hits:               32 /    84 (38.10%)
    Direct:           31 /    32 (96.88%)
    Preprocessed:      1 /    32 ( 3.12%)
  Misses:             52 /    84 (61.90%)
Uncacheable calls: 22421 / 22505 (99.63%)
Local storage:
  Cache size (GB):  0.00 /  5.00 ( 0.10%)
```
This behavior was previously way better, since it seems that ccache itself does not even create the cache anymore.

When I use buildcache (https://github.com/mbitsnbites/buildcache), the hitrate, even using debug configs at the kernel, is at around 50%+.

### Expected behavior ###

ccache should generate the cache correctly and hits.

### Environment ###

ccache version 4.7.2

CachyOS (Archlinux based)
GCC 12.2.0 binutils 2.39
BTRFS on a nvme

**Comment by jrosdahl** [comment] 2022-11-02 20:40
Duplicate of #1203

**Closed by jrosdahl** 2022-11-02 20:40 UTC
Labels: bug
