### ISSUE TITLE
ccache swallows error from gcc with -Wmisleading-indentation

### ISSUE THREAD

**Issue by ragnar-ouchterlony** [ccache/ccache#105] opened 2016-06-23 14:47 UTC
I compiled the attached [ccache.c](https://github.com/ccache/ccache/files/330191/ccache.txt) using the commands in [ccache_build.txt](https://github.com/ccache/ccache/files/330187/ccache_build.txt). As seen in that file, I get the expected error when building using gcc directly, but not when building via ccache. I would expect to get the error also when building via ccache.

ccache used is 3.2.4.
gcc used is 6.1.1.
system is Fedora 24.

(I had to rename ccache.c to ccache.txt because github didn't like the file type ...)

**Comment by itensionanders** [comment] 2016-06-26 13:33
Sounds like this is similar to the other warnings that require the original code (not preprocessed) ?

After the preprocessing, it ends up looking like:
```
int foo(int a)
{
  do { if ((a)) (a) += 1; else (a) += 2; (a) += 1; } while (0);
  return a;
}

```
Not much indentation left to complain about, there ?

So if you want to use any such warnings, you need to use run_second_cpp ($CCACHE_CPP2).

**Comment by itensionanders** [comment] 2016-06-26 13:47
This is the same issue as in #93, maybe it needs to be documented more thoroughly ?

**Comment by ragnar-ouchterlony** [comment] 2016-06-27 14:45
Prehaps I should file a bug against gcc, because it seems gcc does not give the warning when run on the preprocessed output as you say.

I tried setting CCACHE_CPP2, but didn't produce the error:

CCACHE_CPP2=y ccache -- /usr/bin/gcc -ftrack-macro-expansion=0 -Wmisleading-indentation -Werror -o ccache.o -c ccache.c

**Comment by itensionanders** [comment] 2016-07-03 08:26
@ragnar-ouchterlony : so you mean that it works fine with $CCACHE_CPP2

I don't think it's a bug. It's more that people nowadays want the compiler to give warnings on non-code like comments and whitespace, and all those are ("was" ?) being stripped out by the preprocessor. For clang it is even worse, since it saves a *ton* of internal state before going from "cpp" to "cc" mode. Since none of this state is kept, it also takes a long time to have to do all that parsing over again.

Fortunately you only have to spend that when getting cache misses, direct hits are still cheap.

**Comment by jrosdahl** [comment] 2016-07-19 15:36
Closing this since it's a duplicate of #93.

**Closed by jrosdahl** 2016-07-19 15:36 UTC
