### ISSUE TITLE
Create symlinks instead of copy obj files to speed up

### ISSUE THREAD

**Issue by skryv-softserveinc** [ccache/ccache#254] opened 2018-04-13 12:23 UTC
COW FS's may use `cp --reflink` alternatively

**Comment by afbjorklund** [comment] 2018-04-13 16:47
Maybe related to #213 (it talks about btrfs) ? Note that ccache has support for hardlinks already...

If you would create symlinks to the cache and the cache is cleaned, the symlink would be dangling.

**Comment by jrosdahl** [comment] 2018-04-17 20:13
As explained by @afbjorklund, creating symlinks isn't a good idea. Closing as a duplicate of #213.

**Closed by jrosdahl** 2018-04-17 20:13 UTC
Labels: discussion, duplicate, enhancement
