### ISSUE TITLE
C99 requires -D_XPG6 on Solaris

### ISSUE THREAD

**Issue by dago** [ccache/ccache#148] opened 2016-11-07 13:22 UTC
I am trying to compile ccache 3.3.3 on Solaris 10 with Oracle Studio 12 and get a compilation error.

The required flags for C99 are detected as follows:
```
checking for /opt/SUNWspro/bin/cc option to accept ISO C89... none needed
checking for /opt/SUNWspro/bin/cc option to accept ISO C99... -D_STDC_C99=
checking how to run the C preprocessor... /opt/SUNWspro/bin/cc -D_STDC_C99= -E
```
which results in a compilation error with inconsistently set preprocessor flags:
```
/opt/SUNWspro/bin/cc -D_STDC_C99= -DHAVE_CONFIG_H -DSYSCONFDIR=/etc/opt/csw -I. -I. -I/opt/csw/include -I./zlib -xO3 -m32 -xarch=sparc -O -c -o args.o args.c
"/usr/include/sys/feature_tests.h", line 337: #error: "Compiler or options invalid for pre-UNIX 03 X/Open applications  and pre-2001 POSIX applications"
```

The addition of `-D_XPG6` to `CPPFLAGS` solves the issue.

**Comment by afbjorklund** [comment] 2016-11-13 16:26
Seems like `AC_USE_SYSTEM_EXTENSIONS` will get rid of this, but then again it might be overkill...
https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/Posix-Variants.html

If used, we also need `AC_PREREQ(2.60)` (up from current 2.52)

Also hard to fix all these proprietary platforms bugs, without access to a proper compile farm.
Whether it is Windows or Macintosh or Solaris, it might probably need "downstream" porters ?

I'll leave it to @jrosdahl, how to best address this SunOS issue.

**Comment by afbjorklund** [comment] 2016-11-13 16:31
Possibly related to 9485354a5542f901dbca9f96930d036bdbdaaf8b

**Comment by afbjorklund** [comment] 2016-11-13 16:40
Maybe moving `m4_include(m4/feature_macros.m4)` above `AC_PROG_CC_C99` is enough ?

**Comment by dago** [comment] 2016-11-13 16:47
Hi Anders,

Am 13.11.2016 um 17:26 schrieb Anders Björklund <notifications@github.com>:
> Seems like AC_USE_SYSTEM_EXTENSIONS will get rid of this, but then again it might be overkill...
> https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/Posix-Variants.html
> 
> If used, we also need AC_PREREQ(2.60) (up from current 2.52)
> 
> Also hard to fix all these proprietary platforms bugs, without access to a proper compile farm.
> Whether it is Windows or Macintosh or Solaris, it might probably need "downstream" porters ?

I’ll happily provide you with an account on our build farm:
  https://www.opencsw.org/extend-it/signup/to-upstream-maintainers/

Also I can setup continuous builds if considered useful:
  https://buildfarm.opencsw.org/buildbot/waterfall


Best regards

  — Dago

**Comment by afbjorklund** [comment] 2016-11-13 17:06
Thanks for the offer! It would be nice if it would integrate with [Travis](https://travis-ci.org/) (somehow) ?
Like the [Appveyor](https://appveyor.com) (for Windows), it's a bit of a hassle to have multiple systems...

For now, trying out the slight `configure.ac` adjustment would be enough:

``` diff
diff --git a/configure.ac b/configure.ac
index a35fac0..4095f4b 100644
--- a/configure.ac
+++ b/configure.ac
@@ -20,6 +20,8 @@ AC_SUBST(extra_libs)
 AC_SUBST(include_dev_mk)
 AC_SUBST(test_suites)
 
+m4_include(m4/feature_macros.m4)
+
 dnl Checks for programs.
 AC_PROG_CC_C99
 if test "$ac_cv_prog_cc_c99" = no; then
@@ -34,8 +36,6 @@ if test -z "$AR"; then
     AC_MSG_ERROR(cannot find ar)
 fi
 
-m4_include(m4/feature_macros.m4)
-
 # If GCC, turn on warnings.
 if test "x$GCC" = "xyes"; then
     CFLAGS="$CFLAGS -Wall -W"

```

**Comment by afbjorklund** [comment] 2016-11-13 17:25
Found that there already is a maintainer: https://www.opencsw.org/packages/CSWccache/

And that besides c99, you also have some problems with "bash" and "seq"* not being available ?
someone suggests using `dc` instead: http://www.vleo.net/seq-equivalent-on-solarismacosx/

The new test.sh uses #!/bin/sh, though.

**Comment by afbjorklund** [comment] 2016-11-13 19:43
@dago: Looks like @jrosdahl already has OpenCSW access...
Added the test code to 971f7ae, if you want to try it (c99+seq) ?

**Comment by afbjorklund** [comment] 2016-11-13 20:00
Also looks like Travis has "known issues" with non-Linux (/non-Mac) platforms.
Such as travis-ci/travis-ci#1818 (FreeBSD) or travis-ci/travis-ci#1368 (illumos)

**Comment by dago** [comment] 2016-11-14 08:27
@afbjorklund Haha, yes, there is a maintainer at OpenCSW, me :-)

Regarding the `seq` thing: that is not really a problem for me as we also have a package for GNU Coreutils which provides that. However, for stock-Solaris users it may indeed be useful to not rely on 3rd party stuff.

What we could do for building is integrating our buildbot with ccache Github so builds are triggered on commits and pull requests. We already did this for other projects like collectd and wget. You just need to enable Webhooks and generate a token to feed back the build status.

**Comment by afbjorklund** [comment] 2016-11-14 20:45
I'll let @jrosdahl (the maintainer) decide. Did the patches work out for you ?

**Comment by afbjorklund** [comment] 2016-11-14 21:27
Okay, running [illumos](http://www.illumos.org/) I could reproduce your issues with the bashist test.sh script:

```
./test.sh[143]: local: not found [No such file or directory]
Running test suite ./test.sh[164]: SUITE_: not found [No such file or directory]
```

But I didn't see the other Oracle stuff, due to `/usr/bin/gcc` and `/usr/gnu/bin/seq`

----
Supporting that compiler seems about as much fun as supporting Visual Studio. Sorry...
Then again I do think the patch _should_ work, since it adds `#define _XOPEN_SOURCE 600`

**Comment by jrosdahl** [comment] 2017-02-12 14:11
> For now, trying out the slight configure.ac adjustment would be enough:

Applied on 3.3-maint and master now. Thanks, @afbjorklund! @dago: Does this fix the problem?

Regarding supporting Solaris and other non-mainstream Unixes: I used to try to keep the systems in Samba's build farm (including OpenBSD, Tru64, IRIX, NetBSD, Solaris, etc.) happy, but the compile farm has been defunct for several years and I currently have neither time nor interest in trying to get ccache to compile on the mentioned systems. I welcome simple patches to fix things, but I will be less inclined to accept more intrusive fixes, e.g. like writing `test.sh` to be compatible with Solaris's non-POSIX `/bin/sh`.

**Comment by dago** [comment] 2017-02-13 13:11
I just tried `master` with Solaris Studio 12.4 `CC=/opt/solarisstudio12.4/bin/cc` and get
```
checking whether /opt/solarisstudio12.4/bin/cc accepts -g... yes
checking for /opt/solarisstudio12.4/bin/cc option to accept ISO C89... none needed
checking for /opt/solarisstudio12.4/bin/cc option to accept ISO C99... unsupported
configure: error: cannot find a C99-compatible compiler
```
When setting `CC="/opt/solarisstudio12.4/bin/cc -std=c99"` it fails even earlier with
```
dam@unstable10s [unstable10s]:/home/dam/work/ccache > ./configure                                       
configure: Configuring ccache
checking build system type... sparc-sun-solaris2.10
checking host system type... sparc-sun-solaris2.10
checking for gcc... /opt/solarisstudio12.4/bin/cc -std=c99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/home/dam/work/ccache':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

Using `CC=/opt/solarisstudio12.4/bin/c99` leads to
```
configure:2991: /opt/solarisstudio12.4/bin/c99 -o conftest    conftest.c  >&5
"/usr/include/sys/feature_tests.h", line 337: #error: "Compiler or options invalid for pre-UNIX 03 X/Open applications  and pre-2001 POSIX applications"
c99: acomp failed for conftest.c
```

Or did I miss some setting you suggested?

**Comment by dago** [comment] 2017-03-09 08:51
I just verified with 3.3.4 that it shows the same behaviour than what I described above.

**Comment by afbjorklund** [comment] 2017-03-10 18:53
Did you have a more working patch ? Like the Mac stuff, it is hard for us to test this.
(I suppose installing gcc or some other C99 compiler is not really an option for you)

**Comment by jrosdahl** [comment] 2018-01-27 21:23
I will not dedicate time to this issue, but I'll gladly apply any fix if it's clean enough.

**Comment by jrosdahl** [comment] 2019-08-16 17:39
Closing this issue now due to lack of progress. Also, the next ccache version will require a C++11 compiler.

**Closed by jrosdahl** 2019-08-16 17:39 UTC
Labels: help wanted, portability
