### ISSUE TITLE
Diagnostics color option can still be improperly accepted

### ISSUE THREAD

**Issue by malfet** [ccache/ccache#1275] opened 2023-04-12 17:33 UTC
### How to reproduce ###
- Install ccache on CentOS 9 and run steps from https://github.com/ccache/ccache/issues/740 
- Alternative running following commands on fresh Ubuntu22.04 also do the trick:
```shell
$ apt update; apt install -y g++ ccache
$ ln -f /usr/bin/x86_64-linux-gnu-g++-11 /usr/bin/c++
$ ln -sf /usr/bin/ccache /usr/local/bin/c++
$ echo 'int main() { return 0; }' >src.cxx
$  /usr/local/bin/c++ -c src.cxx
$ /usr/local/bin/c++ -fcolor-diagnostics -c src.cxx
```
### Actual behavior ###
Invocation of `-fcolor-diagnostics` on ccache wrapped gcc compiler succeeds

### Expected behavior ###
It should fail

### Environment ###
ccache version 4.5.1

I think essential part here, is that it reproduces on systems that do not follow the `/etc/alternatives` patterns of symlinking `cc`/`c++` to `gcc`/`g++`, which confuses compiler detection logic.

Discovered while debugging https://github.com/pytorch/pytorch/issues/83500

**Comment by jrosdahl** [comment] 2023-04-18 07:42
Thanks for the bug report. This is a duplicate of #1116, which was fixed in ccache 4.6.2.

**Closed by jrosdahl** 2023-04-18 07:42 UTC
Labels: bug
