### ISSUE TITLE
Multiple input files

### ISSUE THREAD

**Issue by kreuzerkrieg** [ccache/ccache#853] opened 2021-05-27 07:27 UTC
For some reason I've started to hit "Multiple input files" in my compilation

> [2021-05-27T07:08:28.597670 3797 ] Hostname: 3e4e251fc12b
> [2021-05-27T07:08:28.597694 3797 ] Working directory: /root/project/obj-x86_64-linux-gnu
> [2021-05-27T07:08:28.598510 3797 ] Multiple input files: /usr/bin/clang++-11 and ../src/DataTypes/DataTypeCustomIPv4AndIPv6.cpp
> [2021-05-27T07:08:28.598547 3797 ] Failed; falling back to running the real compiler
> [2021-05-27T07:08:28.598553 3797 ] Executing /usr/bin/prlimit --as=10000000000 --data=5000000000 --cpu=600 /usr/bin/clang++-11 -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=7 -DAWS_SDK_VERSION_PATCH=231 -DBOOST_ASIO_STANDALONE=1 -DBUNDLED_STATIC_JEMALLOC=1 -DCARES_STATICLIB -DCONFIGDIR="" -DENABLE_OPENSSL_ENCRYPTION -DHAVE_CONFIG_H -DHYRISE_DEBUG=0 -DLIBSASL_EXPORTS=1 -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DOBSOLETE_CRAM_ATTR=1 -DOBSOLETE_DIGEST_ATTR=1 -DPLUGINDIR="" -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_EPOLL -DPOCO_OS_FAMILY_UNIX -DSASLAUTHD_CONF_FILE_DEFAULT="" -DSNAPPY_CODEC_AVAILABLE -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DUNALIGNED_OK -DUSE_FASTMEMCPY=1 -DUSE_JEMALLOC=1 -DUSE_REPLXX=1 -DUSE_XXHASH=1 -DWITH_COVERAGE=0 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -D__CLANG_SUPPORT_DYN_ANNOTATION__ -I../contrib/sentry-native/include -Iincludes/configs -I../src -Isrc -Isrc/Core/include -I../base/common/.. -Ibase/common/.. -I../contrib/cityhash102/include -I../contrib/FastMemcpy -I../contrib/cctz/include -Icontrib/zlib-ng -I../contrib/zlib-ng -I../base/pcg-random/. -I../contrib/aws-c-common/include -I../contrib/aws-c-event-stream/include -Icontrib/aws-s3-cmake/include -I../contrib/aws/aws-cpp-sdk-sts/include -I../contrib/aws/aws-cpp-sdk-glue/include -I../contrib/hyrise/src/lib -I. -I../contrib/lz4/lib -I../contrib/hyrise/third_party/sql-parser/src -I../contrib/hyrise/third_party/uninitialized_vector -I../contrib/hyrise/third_party/magic_enum/include -Icontrib/cyrus-sasl-cmake -I../contrib/krb5/src/include -Icontrib/krb5-cmake/include -I../base/mysqlxx/.. -I../contrib/mariadb-connector-c/include -Icontrib/mariadb-connector-c/include -Icontrib/grpc/third_party/cares/cares -I../contrib/grpc/third_party/cares/cares -I../contrib/abseil-cpp -I../contrib/libuv/include -I../contrib/duckdb/src/include -isystem ../contrib/rocksdb/include -isystem ../contrib/orc/c++/include -isystem contrib/orc/c++/include -isystem ../contrib/libhdfs3/include -isystem ../contrib/protobuf/src -isystem ../contrib/sparsehash-c11 -isystem ../contrib/openldap-cmake/linux_x86_64/include -isystem ../contrib/openldap/include -isystem ../contrib/avro/lang/c++/include -isystem ../contrib/miniselect/include -isystem ../contrib/pdqsort -isystem ../contrib/jwt-cpp/include -isystem ../contrib/llvm/llvm/include -isystem contrib/llvm/llvm/include -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/antlr4-runtime -isystem ../contrib/fast_float/include -isystem ../contrib/msgpack-c/include -isystem ../contrib/aws/aws-cpp-sdk-s3/include -isystem ../contrib/aws/aws-cpp-sdk-core/include -isystem ../contrib/xz/src/liblzma/api -isystem ../contrib/zstd/lib -isystem ../contrib/re2 -isystem ../contrib/boost -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/NetSSL_OpenSSL/include -isystem ../contrib/poco/Crypto/include -isystem ../contrib/boringssl/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/JSON/include -isystem ../contrib/poco/XML/include -isystem ../contrib/replxx/include -isystem ../contrib/fmtlib-cmake/../fmtlib/include -isystem ../contrib/double-conversion -isystem ../contrib/dragonbox/include -isystem contrib/re2_st -isystem ../contrib/croaring/cpp -isystem ../contrib/croaring/include -isystem ../contrib/jemalloc-cmake/include -isystem ../contrib/libdivide/. -isystem ../contrib/hyrise/third_party/nlohmann_json/single_include -isystem ../contrib/cppkafka/include -isystem ../contrib/librdkafka-cmake/include -isystem ../contrib/librdkafka/src -isystem contrib/librdkafka-cmake/auxdir -isystem ../contrib/AMQP-CPP/include -isystem ../contrib/NuRaft/include -isystem ../contrib/poco/MongoDB/include -isystem ../contrib/icu/icu4c/source/i18n -isystem ../contrib/icu/icu4c/source/common -isystem ../contrib/capnproto/c++/src -isystem ../contrib/arrow/cpp/src -isystem ../contrib/arrow-cmake/cpp/src -isystem contrib/arrow-cmake/cpp/src -isystem ../contrib/avro/lang/c++/api -isystem ../contrib/grpc/include -isystem src/Server/grpc_protos -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -g -O2 -fdebug-prefix-map=/root/project=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wdate-time -fdiagnostics-color=always -std=gnu++2a -fsized-deallocation -gdwarf-aranges -pipe -msse4.1 -msse4.2 -mpopcnt -Wall -Wno-unused-command-line-argument -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Werror -Wextra -Wframe-larger-than=65536 -Wpedantic -Wno-vla-extension -Wno-zero-length-array -Wno-c11-extensions -Wcomma -Wconditional-uninitialized -Wcovered-switch-default -Wdeprecated -Wembedded-directive -Wempty-init-stmt -Wextra-semi-stmt -Wextra-semi -Wgnu-case-range -Winconsistent-missing-destructor-override -Wnewline-eof -Wold-style-cast -Wrange-loop-analysis -Wredundant-parens -Wreserved-id-macro -Wshadow-field -Wshadow-uncaptured-local -Wshadow -Wstring-plus-int -Wundef -Wunreachable-code-return -Wunreachable-code -Wunused-exception-parameter -Wunused-macros -Wunused-member-function -Wzero-as-null-pointer-constant -Weverything -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c99-extensions -Wno-conversion -Wno-ctad-maybe-unsupported -Wno-deprecated-dynamic-exception-spec -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-nested-anon-types -Wno-packed -Wno-padded -Wno-return-std-move-in-c++11 -Wno-shift-sign-overflow -Wno-sign-conversion -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -O2 -g -DNDEBUG -O3 -fno-pie -D OS_LINUX -nostdinc++ -Wno-extra-semi -Wno-inconsistent-missing-destructor-override -pthread -MD -MT src/CMakeFiles/dbms.dir/DataTypes/DataTypeCustomIPv4AndIPv6.cpp.o -MF src/CMakeFiles/dbms.dir/DataTypes/DataTypeCustomIPv4AndIPv6.cpp.o.d -o src/CMakeFiles/dbms.dir/DataTypes/DataTypeCustomIPv4AndIPv6.cpp.o -c ../src/DataTypes/DataTypeCustomIPv4AndIPv6.cpp
> 

Is it a bug in ccache or in the user? :) for some reason it thinks that the compiler itself is a source file.

### Environment ###
ccache version 3.7.7
Ubuntu 20.04

Additional input:
When just building the same project - cmake+ninja it works as expected
Once the same project is build using `debuild` it exhibits above behaviour. Clearly it has something to to with the way the environment variables are passed to the `debuild`, but regardless, why the compiler itself is considered as a source file?

**Comment by afbjorklund** [comment] 2021-05-28 09:35
It seems that you have added another command in front of your real compiler:

`/usr/bin/prlimit --as=10000000000 --data=5000000000 --cpu=600 /usr/bin/clang++-11`

You probably want to do that in a shell wrapper, and use that script as the compiler ?

**Comment by kreuzerkrieg** [comment] 2021-05-28 10:04
Looks like it is not me, but the `debuild`. And looks like there is a way to solve it
https://github.com/ClickHouse/ClickHouse/blob/master/CMakeLists.txt#L71-L79

On the other hand, why prepending the call to the compiler interpreted by ccache as additional source

**Comment by jrosdahl** [comment] 2021-05-29 17:43
> Looks like it is not me, but the `debuild`.

Right.

> And looks like there is a way to solve it
> https://github.com/ClickHouse/ClickHouse/blob/master/CMakeLists.txt#L71-L79

Yes, ccache needs to get the real compiler as the first argument.

Just a comment regarding _"Another way would be to use --ccache-skip option before clang++-11 to make# ccache ignore it."_ from the code you linked: No, that's not a good solution since then ccache will still treat prlimit as the compiler and for instance use the prlimit binary's mtime to recognize the compiler, etc.

> On the other hand, why prepending the call to the compiler interpreted by ccache as additional source

The interface to use ccache is like this: `ccache compiler [compiler options ...]`. Ccache then parses the compiler options part as a compiler would parse them. A part of that parsing is done to figure out which is the source code file argument (ccache only supports compilation of one source per command). That's done by finding _the_ positional argument. If you run `ccache prlimit /usr/bin/clang++ example.c` then there are _two_ positional arguments (clang++ and example.c), which leads to the "Multiple input files" error.

Closing this as "works as intended".

**Closed by jrosdahl** 2021-05-29 17:43 UTC
Labels: bug, closed: works as intended
