### ISSUE TITLE
'preprocessor error' with GCC_COLORS and gcc < 4.9

### ISSUE THREAD

**Issue by jerome-pouiller** [ccache/ccache#297] opened 2018-08-14 08:13 UTC
On my environment, call to ccache only increment 'preprocessor error' stat. After stracing ccache, I noticed that it add "-fdiagnostics-color" to gcc command line. Indeed, my environment contains GCC_COLORS. Since my gcc is < 4.9, this option make an error.

Indeed, everything works well once I unset GCC_COLOR.

After quickly looking at the code (to write a patch), it seems issue is not easy to solve. However, I think ccache should detect this issue and provide to use some hint to solve it.

**Comment by afbjorklund** [comment] 2018-08-14 15:45
Yeah, this one is easy to reproduce:
```
[2018-08-14T17:41:56.342322 22094] Running preprocessor
[2018-08-14T17:41:56.342339 22094] Executing /usr/bin/gcc-4.8 -fdiagnostics-color -E test.c
[2018-08-14T17:41:56.344373 22094] Preprocessor gave exit status 1
```

It is also a known issue, though:
``` C
                       // GCC has it since 4.9, but that'd require detecting what GCC version is
                        // used for the actual compile. However it requires also GCC_COLORS to be
                        // set (and not empty), so use that for detecting if GCC would use
                        // colors.
                        if (getenv("GCC_COLORS") && getenv("GCC_COLORS")[0] != '\0') {
                                args_add(stripped_args, "-fdiagnostics-color");
                                cc_log("Automatically enabling colors");
                        }

```

So in order to support gcc-4.8, we need some kind of "compatibility mode" to be enabled.
Preferrably we would not have to parse the compiler version, but maybe another env var ?

**Comment by afbjorklund** [comment] 2018-08-14 15:56
What we are trying to achieve is for ccache to returned color output, even from the cache.

That is, instead of this:
``` txt
 cpp.c:1:2: error: invalid preprocessing directive #foo
 #foo
  ^
```

It should save this: (the color escapes are _supposed_ to look funny like that)
``` txt
^[[01m^[[Kcpp.c:1:2:^[[m^[[K ^[[01;31m^[[Kerror: ^[[m^[[Kinvalid preprocessing directive #foo
 #foo
^[[01;32m^[[K  ^^[[m^[[K
```

See #224 for improvement suggestions, that are better than simply unsetting GCC_COLORS

**Comment by jrosdahl** [comment] 2018-08-23 20:17
Yes, this is sort of a duplicate of #224. We currently sacrifice usability for GCC <4.9 users in order to enable colored output out of the box for GCC ≥4.9 users.

**Comment by jrosdahl** [comment] 2018-08-23 20:17
@jerome-pouiller: Closing this, please subscribe to #224 instead.

**Closed by jrosdahl** 2018-08-23 20:17 UTC
Labels: bug, wontfix
