### ISSUE TITLE
rsp file handling does not seem to work

### ISSUE THREAD

**Issue by mumpitzstuff** [ccache/ccache#1204] opened 2022-10-31 18:10 UTC
### How to reproduce ###

```[2022-10-31T18:36:12.791087 26500] === CCACHE 4.7.2 STARTED =========================================
[2022-10-31T18:36:12.791087 26500] Configuration file: C:\work\ccache_data\ccache.conf
[2022-10-31T18:36:12.791087 26500] System configuration file: C:\ProgramData\ccache\ccache.conf
[2022-10-31T18:36:12.791087 26500] Config: (default) absolute_paths_in_stderr = false
[2022-10-31T18:36:12.791087 26500] Config: (default) base_dir = 
[2022-10-31T18:36:12.791087 26500] Config: (environment) cache_dir = C:\work\ccache_data
[2022-10-31T18:36:12.791087 26500] Config: (environment) compiler = C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe
[2022-10-31T18:36:12.791087 26500] Config: (default) compiler_check = mtime
[2022-10-31T18:36:12.791087 26500] Config: (C:\work\ccache_data\ccache.conf) compiler_type = msvc
[2022-10-31T18:36:12.791087 26500] Config: (default) compression = true
[2022-10-31T18:36:12.791087 26500] Config: (default) compression_level = 0
[2022-10-31T18:36:12.791087 26500] Config: (default) cpp_extension = 
[2022-10-31T18:36:12.791087 26500] Config: (C:\work\ccache_data\ccache.conf) debug = true
[2022-10-31T18:36:12.791087 26500] Config: (default) debug_dir = 
[2022-10-31T18:36:12.791087 26500] Config: (default) depend_mode = false
[2022-10-31T18:36:12.791087 26500] Config: (default) direct_mode = true
[2022-10-31T18:36:12.791087 26500] Config: (default) disable = false
[2022-10-31T18:36:12.791087 26500] Config: (default) extra_files_to_hash = 
[2022-10-31T18:36:12.791087 26500] Config: (default) file_clone = false
[2022-10-31T18:36:12.791087 26500] Config: (default) hard_link = false
[2022-10-31T18:36:12.791087 26500] Config: (default) hash_dir = true
[2022-10-31T18:36:12.791087 26500] Config: (default) ignore_headers_in_manifest = 
[2022-10-31T18:36:12.791087 26500] Config: (default) ignore_options = 
[2022-10-31T18:36:12.791087 26500] Config: (default) inode_cache = true
[2022-10-31T18:36:12.791087 26500] Config: (default) keep_comments_cpp = false
[2022-10-31T18:36:12.791087 26500] Config: (default) limit_multiple = 0.8
[2022-10-31T18:36:12.791087 26500] Config: (C:\work\ccache_data\ccache.conf) log_file = c:\work\ccache_data\ccache.log
[2022-10-31T18:36:12.791087 26500] Config: (default) max_files = 0
[2022-10-31T18:36:12.791087 26500] Config: (C:\work\ccache_data\ccache.conf) max_size = 30.0G
[2022-10-31T18:36:12.791087 26500] Config: (default) msvc_dep_prefix = Note: including file:
[2022-10-31T18:36:12.791087 26500] Config: (default) namespace = 
[2022-10-31T18:36:12.791087 26500] Config: (default) path = 
[2022-10-31T18:36:12.791087 26500] Config: (default) pch_external_checksum = false
[2022-10-31T18:36:12.791087 26500] Config: (default) prefix_command = 
[2022-10-31T18:36:12.791087 26500] Config: (default) prefix_command_cpp = 
[2022-10-31T18:36:12.791087 26500] Config: (default) read_only = false
[2022-10-31T18:36:12.791087 26500] Config: (default) read_only_direct = false
[2022-10-31T18:36:12.791087 26500] Config: (default) recache = false
[2022-10-31T18:36:12.791087 26500] Config: (default) remote_only = false
[2022-10-31T18:36:12.791087 26500] Config: (default) remote_storage = 
[2022-10-31T18:36:12.791087 26500] Config: (default) reshare = false
[2022-10-31T18:36:12.791087 26500] Config: (default) run_second_cpp = true
[2022-10-31T18:36:12.791087 26500] Config: (default) sloppiness = 
[2022-10-31T18:36:12.791087 26500] Config: (default) stats = true
[2022-10-31T18:36:12.791087 26500] Config: (default) stats_log = 
[2022-10-31T18:36:12.791087 26500] Config: (default) temporary_dir = C:\work\ccache_data/tmp
[2022-10-31T18:36:12.791087 26500] Config: (default) umask = 
[2022-10-31T18:36:12.791087 26500] Command line: c:\work\ccache_test\CL.exe @C:\Users\<user>\AppData\Local\Temp\tmp13fa68e85ce7416f9142ef38955a3673.rsp
[2022-10-31T18:36:12.811241 26500] Hostname: <hostname>
[2022-10-31T18:36:12.811241 26500] Working directory: C:/work/<project>
[2022-10-31T18:36:12.811241 26500] Compiler type: msvc
[2022-10-31T18:36:12.811241 26500] Multiple input files: <first file in rsp file> and <second file in rsp file>
[2022-10-31T18:36:12.811241 26500] Multiple input files: <first file in rsp file> and <third file in rsp file>
and so on...
[2022-10-31T18:36:13.093368 26500] Failed; falling back to running the real compiler
[2022-10-31T18:36:13.093368 26500] Executing C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe @C:\Users\<user>\AppData\Local\Temp\tmp13fa68e85ce7416f9142ef38955a3673.rsp
[2022-10-31T18:36:13.093368 26500] Result: multiple_source_files
[2022-10-31T18:36:13.093368 26500] Acquiring C:\work\ccache_data/8/4/stats.lock
[2022-10-31T18:36:13.111500 26500] Acquired C:\work\ccache_data/8/4/stats.lock
[2022-10-31T18:36:13.172007 26500] Releasing C:\work\ccache_data/8/4/stats.lock
[2022-10-31T18:36:13.174037 26500] Released C:\work\ccache_data/8/4/stats.lock
[2022-10-31T18:36:20.616813 23776] Got result key from preprocessor
[2022-10-31T18:36:20.616813 23776] Result key: 0306l3d3gj24p77ajrhdcm03egnt1vneo
[2022-10-31T18:36:20.616813 23776] No 0306l3d3gj24p77ajrhdcm03egnt1vneo in local storage
[2022-10-31T18:36:20.616813 23776] Running real compiler```

The cache is near empty if the builds gets completed:

```
Cacheable calls:     39 /   126 (30.95%)
  Hits:               0 /    39 ( 0.00%)
    Direct:           0
    Preprocessed:     0
  Misses:            39 /    39 (100.0%)
Uncacheable calls:   87 /   126 (69.05%)
Local storage:
  Cache size (GB): 0.00 / 30.00 ( 0.01%)
  Cleanups:          14
```

`<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets">
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup />
  <PropertyGroup Label="Globals">
    <CLToolPath>c:\work\ccache_test\</CLToolPath>
    <UseMultiToolTask>true</UseMultiToolTask>
    <TrackFileAccess>false</TrackFileAccess>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <DebugInformationFormat>OldStyle</DebugInformationFormat>
      <ForcedIncludeFiles />
      <ObjectFileName>$(IntDir)%(Filename).obj</ObjectFileName>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>`

For me it looks like the ccache gets called and the real compiler afterwards too. "c:\work\ccache_test" is not part of the path and i used CCACHE_COMPILER = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe".

It might be just a simple mistake, but i am not able to find the issue. I can provide the full logs if needed or an example rsp file from my project.
Ah and the compilation is finished like expected, just the cached ccache data is missing afterwards.

### Environment ###
<!-- Which ccache version did you use? -->

ccache version 4.7.2

<!-- If applicable, add more info such as compiler, OS and file system below: -->

Visual Studio 2015
Windows 10 (64-Bit)

**Comment by cristianadam** [comment] 2022-10-31 21:01
It worked for me with CMake and the MSBuild generator, see https://github.com/ccache/ccache/discussions/1154#discussioncomment-3611387

You could try it out and compare the `vcxproj` file and see what's missing.

**Comment by mumpitzstuff** [comment] 2022-10-31 22:53
Hmm are you sure that we talk about the same things? I talk about non working rsp file support. Your project seems to have a single cpp file but i can not see if msbuild will generate a rsp file. Anyway i tried that on a huuuuge project which consists of a lot of auto generated makefiles. There is no easy way to enhance them all. The generated rsp files normally also contain more than a single file. It might be the case that the ccache rsp parser do not work for rsp files with more than a single file (i will try to check that in the log file and report my findings later).
On the other hand, i also tried to do exactly the same thing with clcache (which is a bit outdated) and it was running. The rsp parser here was able to split the rsp file into separate compiler calls and everything was fine. I expected that the same would work with ccache, but it does not. And i really just modified the xml file posted above, nothing else (same project, same compiler, just the cache exe was a different one (clcache vs. ccache)).

**Comment by mumpitzstuff** [comment] 2022-10-31 23:09
It looks like the problem occurs if the rsp contains more than a single source file:

With just a single file, it looks fine:
```[2022-10-31T17:37:14.545449 26496] Command line: c:\work\ccache-4.7.2\cl.exe @C:\Users\<user>\AppData\Local\Temp\tmp62bbba346d02404cad73a89e830a314e.rsp
[2022-10-31T17:37:14.786032 26496] Hostname: <host>
[2022-10-31T17:37:14.786032 26496] Working directory: C:/work/<project>
[2022-10-31T17:37:14.786032 26496] Compiler type: msvc
[2022-10-31T17:37:14.788071 26496] Source file: C:\work\<cpp file>
[2022-10-31T17:37:14.788071 26496] Object file: <obj file>
[2022-10-31T17:37:14.979830 26496] Hashing object file directory C:/work/<project>
[2022-10-31T17:37:14.987871 26496] Trying direct lookup
[2022-10-31T17:37:14.989906 26496] Manifest key: 5e5fsjoc72kg5douba80o5pntmn8j2b96
[2022-10-31T17:37:14.989906 26496] No 5e5fsjoc72kg5douba80o5pntmn8j2b96 in local storage
[2022-10-31T17:37:15.018196 26496] Running preprocessor```

**Comment by mumpitzstuff** [comment] 2022-11-01 14:29
Oh i found the following today somewhere deep in the manual: "The compiler was called to compile multiple source files in one go. This is not supported by ccache.".
It seems i have to create a feature request or is there some known workaround available to prevent this behaviour of visual studio?

**Comment by jrosdahl** [comment] 2022-11-06 09:49
> Oh i found the following today somewhere deep in the manual: "The compiler was called to compile multiple source files in one go. This is not supported by ccache.".

It is also mentioned on the [https://ccache.dev front page](https://ccache.dev): _"Only knows how to cache the compilation of a single file. Other types of compilations (multi-file compilation, linking, etc) will silently fall back to running the real compiler. "_

> is there some known workaround available to prevent this behaviour of visual studio?

As I understand it, you need to set `UseMultiToolTask=true`. See [https://github.com/ccache/ccache/wiki/MS-Visual-Studio](https://github.com/ccache/ccache/wiki/MS-Visual-Studio).

But now I see that you already use that according to the issue description (I guess the anonymous XML snippet at the end is some kind of build configuration you use)? If so, I don't know what the problem is. It might help if you posted the relevant parts of the `.rsp` file instead of letting us guess.

> Is it really that complicated to implement such a feature? It does not look that complicated if i look into the source code of clcache. But i do not know that much about ccache and its internal structure, therefore please excuse my question.

I don't know. I haven't really thought much about it – it's just a limitation that has been there from the start (i.e., way before I got involved), and no build systems in the Unix world do compilations of multiple source files as far as I know. If you have any insights, please share them.

**Comment by mumpitzstuff** [comment] 2022-11-13 17:14
UseMultiToolTask is something i already tried without any success. It looks like it gets overruled by something else. My possibilities  are limited because it is a huge company project with more than 50 project files/libraries and thousands of source files.
The rsp files in general seems to consist of a single line (no line breaks). I shortened the following to hide any company details:

`/c /IC:\work\include1 /IC:\work\include2 /IC:\work\include3 /nologo /W3 /WX- /MP /O2 /Ob2 /D WIN32 /D _WINDOWS /D NDEBUG /D _CRT_SECURE_NO_WARNINGS /D _SCL_SECURE_NO_WARNINGS /D SUPPRESS_ASSERTIONS /D __windows /D __CPU_64OPS /D HAS_FLT_INT_TRUNC /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Zc:rvalueCast /GR /Fo"lib.dir\Release\\" /Fd"lib.dir\Release\lib.pdb" /Gd /TP /wd4503 /wd4244 /errorReport:queue  /Zc:referenceBinding /Zc:strictStrings C:\work\file1.cpp C:\work\file2.cpp C:\work\file3.cpp ...`

The include path list can be really huge and the number of source files too. Building a library seems to be triggered only by a single compiler call, which then contains all cpp files in the form of an rsp file.

**Comment by jrosdahl** [comment] 2022-11-13 19:02
Thanks. Then it doesn't look like a problem with handling RSP files. Are you OK with closing this issue?

**Closed** 2023-01-11 20:05 UTC
Labels: bug, awaiting feedback, compiler: msvc
