### ISSUE TITLE
rsp file support?

### ISSUE THREAD

**Issue by zmike** [ccache/ccache#390] opened 2019-04-23 13:24 UTC
I am doing some building on Windows (with mingw) and my build system is setting the link command to `ccache cc`. This is fine, but on Windows there are very strict command length limits. In order to work around this, it is typical to use .rsp files with the full command and pass them directly to the exe (e.g., `ccache cc @file.rsp`.

With this syntax, the contents of the file are passed directly to the new process, and this bypasses the command length limits.

Unfortunately, it seems that ccache does not correctly preserve this mechanism. When ccache drops through to the actual command (i.e., `cc @file.rsp`), it seems to be passing the full command--including the contents of the rsp file. This ends up violating the command length restriction and causes the build to fail.

When performing the underlying command, ccache should pass it **exactly** as it was received and not as it was expanded.

**Comment by jrosdahl** [comment] 2019-04-23 16:26
Hi, this is a duplicate of #95.

**Closed by jrosdahl** 2019-04-23 16:26 UTC

**Comment by zmike** [comment] 2019-04-23 16:33
Oh thanks, I didn't see that.
