### ISSUE TITLE
High cache miss with shared cache on NFS

### ISSUE THREAD

**Issue by sebpot** [ccache/ccache#194] opened 2017-10-03 14:25 UTC
Hi, I'm working on sharing ccache between multiple macOS machines through NFS. I have a Linux machine with NFS server, which exports one directory:
```
/exports/cache 10.0.0.0/8(rw,async,no_subtree_check,insecure,all_squash,anonuid=123,anongid=123)
```

Please note that there is anonymous access enabled (`all_squash` with `anonuid` and `anongid`), so no matter what user connects to the NFS, files are being created and accessed by the user 123.

There are multiple macOS machines that mount the NFS directory to the mount point, let's call it `<cache-directory>` (the same path on all machines). All of these machines also have the same configuration:
```
cache_dir = <cache-directory>
hard_link = false
hash_dir = false
log_file = /var/log/ccache.log
max_size = 100G
sloppiness = file_macro,include_file_ctime,include_file_mtime,pch_defines,time_macros
temporary_dir = /tmp/cache_temp
umask = 002
```

The macOS machines also use the exact same toolchain (the same version of Apple Clang).

Ccache version: 3.3.4

What I build comes from different git repositories that have common parent repository (there is a synchronization between the parent and the children repositories), so big chunk of code is common in these repositories (usually the difference is a few (usually no more than 100) files, while there are over 7000 source code files being compiled).

Additionally, on each machine I set `CCACHE_BASEDIR` pointing to code root directory, so relative paths on all the machines are exactly the same. When paths are for example:
```
/path/on/machine1/project-team1/code/<source-code>
/path/on/machine2/project-team1/code/<source-code>
/path/on/machine2/project-team2/code/<source-code>
```
the `CCACHE_BASEDIR` is set to `project-team#` directory before build:
```
CCACHE_BASEDIR=/path/on/machine1/project-team1
CCACHE_BASEDIR=/path/on/machine2/project-team1
CCACHE_BASEDIR=/path/on/machine2/project-team2
```
so paths on all machines, no matter the repository (`project-team#`), relative path is always the same:
```
code/<source-code>
```

According to manual:
* https://ccache.samba.org/manual.html#_common_hashed_information
* https://ccache.samba.org/manual.html#_sharing_a_cache
* https://ccache.samba.org/manual.html#_sharing_a_cache_on_nfs

it seems that I meet all the conditions (compilation commands are also the same).

Despite that, the cache hit rate is around 15%. What can I do to make ccache work properly in this configuration, so I could get cache hit rate above 50%?

Please tell me if additional details are needed.

**Comment by mikhirev** [comment] 2017-10-04 14:48
I see the similar issue on Solaris 10 with ccache 3.3.4 from OpenCSW (3.3.4,REV=2017.03.09) and Debian Stretch with ccache 3.3.4 from official repo (3.3.4-1). Seems that `CCACHE_BASEDIR` is broken in 3.3.4.

I've tried a simple test case. Compilation command is `CCACHE_BASEDIR=$PWD CCACHE_LOGFILE=$HOME/tmp/ccache.log ccache gcc -g -pipe -o hello.o -c hello.c`. In the first run I see in log:

```
[2017-10-04T16:43:27.992055 13835] === CCACHE 3.3.4 STARTED =========================================
[2017-10-04T16:43:27.992055 13835] Config: (environment) base_dir = /home/dmitry/tmp
<...>
[2017-10-04T16:43:27.992192 13835] Command line: ccache gcc -g -pipe -o hello.o -c hello.c
[2017-10-04T16:43:27.992211 13835] Hostname: dmikhirev
[2017-10-04T16:43:27.992235 13835] Working directory: /home/dmitry/tmp
[2017-10-04T16:43:27.992284 13835] Source file: hello.c
[2017-10-04T16:43:27.992297 13835] Object file: hello.o
[2017-10-04T16:43:27.992315 13835] Trying direct lookup
[2017-10-04T16:43:27.992345 13835] Looking for object file hash in /home/dmitry/.ccache/5/0/db7a72f2f78f49a986acf8596
fc0ca-252.manifest
[2017-10-04T16:43:28.012238 13835] No such manifest file
[2017-10-04T16:43:28.012283 13835] Did not find object file hash in manifest
[2017-10-04T16:43:28.012384 13835] Running preprocessor
[2017-10-04T16:43:28.012398 13835] Executing /home/dmitry/bin/gcc -pipe -g -E hello.c
[2017-10-04T16:43:28.049511 13835] Got object file hash from preprocessor
[2017-10-04T16:43:28.059029 13835] Object file /home/dmitry/.ccache/5/2/c5f0e5ccd1508a4440fa11016c0f00-17247.o not in
 cache
[2017-10-04T16:43:28.059119 13835] Running real compiler
<...>
```

That's correct, there was no cache entry for this file. Second run:

```
[2017-10-04T16:43:40.055511 13853] === CCACHE 3.3.4 STARTED =========================================
[2017-10-04T16:43:40.055511 13853] Config: (environment) base_dir = /home/dmitry/tmp
<...>
[2017-10-04T16:43:40.055613 13853] Command line: ccache gcc -g -pipe -o hello.o -c hello.c
[2017-10-04T16:43:40.055629 13853] Hostname: dmikhirev
[2017-10-04T16:43:40.055647 13853] Working directory: /home/dmitry/tmp
[2017-10-04T16:43:40.055677 13853] Source file: hello.c
[2017-10-04T16:43:40.055685 13853] Object file: hello.o
[2017-10-04T16:43:40.055699 13853] Trying direct lookup
[2017-10-04T16:43:40.055722 13853] Looking for object file hash in /home/dmitry/.ccache/5/0/db7a72f2f78f49a986acf8596fc0ca-252.manifest
[2017-10-04T16:43:40.056448 13853] Got object file hash from manifest
[2017-10-04T16:43:40.056538 13853] Copying /home/dmitry/.ccache/5/2/c5f0e5ccd1508a4440fa11016c0f00-17247.o to hello.o via hello.o.dmikhirev.13853.f1Q2CG (uncompressed)
[2017-10-04T16:43:40.056787 13853] Created from cache: /home/dmitry/.ccache/5/2/c5f0e5ccd1508a4440fa11016c0f00-17247.o -> hello.o
[2017-10-04T16:43:40.056816 13853] Succeeded getting cached result
<...>
```

That's also correct, cached object used. Then I move the source file to another directory, `cd` there and run the same command again:

```
[2017-10-04T16:46:38.340246 13907] === CCACHE 3.3.4 STARTED =========================================
[2017-10-04T16:46:38.340246 13907] Config: (environment) base_dir = /home/dmitry/tmp/dir
<...>
[2017-10-04T16:46:38.340376 13907] Command line: ccache gcc -g -pipe -o hello.o -c hello.c
[2017-10-04T16:46:38.340396 13907] Hostname: dmikhirev
[2017-10-04T16:46:38.340421 13907] Working directory: /home/dmitry/tmp/dir
[2017-10-04T16:46:38.340467 13907] Source file: hello.c
[2017-10-04T16:46:38.340480 13907] Object file: hello.o
[2017-10-04T16:46:38.340499 13907] Trying direct lookup
[2017-10-04T16:46:38.340535 13907] Looking for object file hash in /home/dmitry/.ccache/9/8/b3c538d768e5e33e548d4d061c9546-256.manifest
[2017-10-04T16:46:38.386512 13907] No such manifest file
[2017-10-04T16:46:38.386550 13907] Did not find object file hash in manifest
[2017-10-04T16:46:38.386638 13907] Running preprocessor
[2017-10-04T16:46:38.386653 13907] Executing /home/dmitry/bin/gcc -pipe -g -E hello.c
[2017-10-04T16:46:38.421264 13907] Got object file hash from preprocessor
[2017-10-04T16:46:38.433310 13907] Object file /home/dmitry/.ccache/b/0/5b4fc96a082819acb1d40f61314814-17251.o not in cache
[2017-10-04T16:46:38.433416 13907] Running real compiler
<...>
```

Cached object should be reused, but it is not. This test case works correctly with ccache 3.1.12 from Debian Jessie.

**Comment by mikhirev** [comment] 2017-10-04 15:09
I've reproduced this issue with ccache from current `3.3-maint` and `master` branches, but was unable to reproduce it with `3.2-maint` branch.

**Comment by mikhirev** [comment] 2017-10-04 15:22
Also reproduced with v3.3.

**Comment by mikhirev** [comment] 2017-10-04 15:45
Well, defining `CCACHE_NOHASHDIR` brings back the desired behavior. Is this bug a "feature"?

**Comment by afbjorklund** [comment] 2017-10-04 18:15
@mikhirev : Yeah, I think this is the same feature as in #175

But strange in that case why your "hash_dir = false" didn't work ?

**Comment by afbjorklund** [comment] 2017-10-04 18:17
For a rationale as to why the default was changed, see:

https://bugzilla.redhat.com/show_bug.cgi?id=759592

**Comment by sebpot** [comment] 2017-10-05 08:47
@mikhirev @afbjorklund Thanks for the hints. Checking if it works properly right now with `CCACHE_NOHASHDIR` variable set. Will post an update once I get the results.

**Comment by sebpot** [comment] 2017-10-06 07:21
Now I'm getting 0.4% hit rate.
I did some log analysis though and the results are interesting.

But setup first:
* one Linux machine as NFS server with single shared directory
* two macOS machines with NFS shared directory mounted in the exact same directory and `ccache.conf` as in the first post
* cleaned cache completely, so there were no files in cache directory and statistics were zeroed, with `ccache -c -C -z`

First, I have run a build on one macOS machine and let it finish. It generated 2.6 GB of cache, over 18000 files in total. Then I zeroed statistics with `ccache -z` and run the build on the second macOS machine. After that build there were over 36000 files in cache (two times more, seems normal taking that the hit rate was 0.4%), but cache size increased to 17.2 GB. So almost all the files were regenerated in cache again for the second build even though they are the same.

I decided to analyse the logs for both builds. Lines containing `Stored in cache:` seem to show what source / preprocessed file is being stored and what is it's destination in cache. I have extracted all such lines from both log files and run `comm` command to find common lines in both of them, and counted the result with `wc`

**Comment by sebpot** [comment] 2017-10-06 07:22
Sorry, closed by mistake.

**Comment by sebpot** [comment] 2017-10-06 08:33
I did a test with one simple file, with cache in NFS directory (`/opt/ccache`).

The file being compiled:
```cpp
#include <iostream>

int main() {
    std::cout << "Hello" << std::endl;
    return 1;
}
```

On two machines I run the same command:
```bash
$ CCACHE_DIR=/opt/ccache \
CCACHE_NOHARDLINK=1 \
CCACHE_NOHASHDIR=1 \
CCACHE_LOGFILE=cache.log \
CCACHE_MAXSIZE=10G \
CCACHE_SLOPPINESS=file_macro,include_file_ctime,include_file_mtime,pch_defines,time_macros \
CCACHE_TEMPDIR=/tmp/ccache_test \
CCACHE_BASEDIR=`pwd` \
ccache clang++ -g -pipe -o main.o -c main.cpp
```

But I get a miss both times.

After first build:
```
$ ccache -s
cache directory                     /opt/ccache
primary config                      /opt/ccache/ccache.conf
stats zero time                     Fri Oct  6 10:19:13 2017
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             1
cache hit rate                      0.00 %
cleanups performed                     0
files in cache                         2
cache size                          88.1 kB
max cache size                      10.0 GB
```
Log:
```
[2017-10-06T10:19:36.966289 7882 ] === CCACHE 3.3.4+59_gef05b88 STARTED =========================================
[2017-10-06T10:19:36.966289 7882 ] Config: (environment) base_dir = /Users/sebpot/test
[2017-10-06T10:19:36.966289 7882 ] Config: (environment) cache_dir = /opt/ccache
[2017-10-06T10:19:36.966289 7882 ] Config: (default) cache_dir_levels = 2
[2017-10-06T10:19:36.966289 7882 ] Config: (default) compiler =
[2017-10-06T10:19:36.966289 7882 ] Config: (default) compiler_check = mtime
[2017-10-06T10:19:36.966289 7882 ] Config: (default) compression = false
[2017-10-06T10:19:36.966289 7882 ] Config: (default) compression_level = 6
[2017-10-06T10:19:36.966289 7882 ] Config: (default) cpp_extension =
[2017-10-06T10:19:36.966289 7882 ] Config: (default) direct_mode = true
[2017-10-06T10:19:36.966289 7882 ] Config: (default) disable = false
[2017-10-06T10:19:36.966289 7882 ] Config: (default) extra_files_to_hash =
[2017-10-06T10:19:36.966289 7882 ] Config: (environment) hard_link = false
[2017-10-06T10:19:36.966289 7882 ] Config: (environment) hash_dir = false
[2017-10-06T10:19:36.966289 7882 ] Config: (default) ignore_headers_in_manifest =
[2017-10-06T10:19:36.966289 7882 ] Config: (default) keep_comments_cpp = false
[2017-10-06T10:19:36.966289 7882 ] Config: (default) limit_multiple = 0.8
[2017-10-06T10:19:36.966289 7882 ] Config: (environment) log_file = cache.log
[2017-10-06T10:19:36.966289 7882 ] Config: (default) max_files = 0
[2017-10-06T10:19:36.966289 7882 ] Config: (environment) max_size = 10.0G
[2017-10-06T10:19:36.966289 7882 ] Config: (default) path =
[2017-10-06T10:19:36.966289 7882 ] Config: (default) prefix_command =
[2017-10-06T10:19:36.966289 7882 ] Config: (default) prefix_command_cpp =
[2017-10-06T10:19:36.966289 7882 ] Config: (default) read_only = false
[2017-10-06T10:19:36.966289 7882 ] Config: (default) read_only_direct = false
[2017-10-06T10:19:36.966289 7882 ] Config: (default) recache = false
[2017-10-06T10:19:36.966289 7882 ] Config: (default) run_second_cpp = true
[2017-10-06T10:19:36.966289 7882 ] Config: (environment) sloppiness = file_macro, include_file_mtime, include_file_ctime, time_macros, pch_defines
[2017-10-06T10:19:36.966289 7882 ] Config: (default) stats = true
[2017-10-06T10:19:36.966289 7882 ] Config: (environment) temporary_dir = /tmp/ccache_test
[2017-10-06T10:19:36.966289 7882 ] Config: (default) umask =
[2017-10-06T10:19:36.966289 7882 ] Config: (default) unify = false
[2017-10-06T10:19:36.967154 7882 ] Command line: ccache clang++ -g -pipe -o main.o -c main.cpp
[2017-10-06T10:19:36.967205 7882 ] Hostname: mac-01
[2017-10-06T10:19:36.967309 7882 ] Working directory: /Users/sebpot/test
[2017-10-06T10:19:36.967389 7882 ] Automatically enabling colors
[2017-10-06T10:19:36.967407 7882 ] Source file: main.cpp
[2017-10-06T10:19:36.967416 7882 ] Object file: main.o
[2017-10-06T10:19:36.967443 7882 ] Trying direct lookup
[2017-10-06T10:19:36.967519 7882 ] Looking for object file hash in /opt/ccache/5/5/f68a8996015d5eea1dfae7c20049e9-262.manifest
[2017-10-06T10:19:36.968379 7882 ] No such manifest file
[2017-10-06T10:19:36.968403 7882 ] Did not find object file hash in manifest
[2017-10-06T10:19:36.968827 7882 ] Running preprocessor
[2017-10-06T10:19:36.968840 7882 ] Executing /usr/bin/clang++ -g -pipe -fcolor-diagnostics -E main.cpp
[2017-10-06T10:19:37.069324 7882 ] Got object file hash from preprocessor
[2017-10-06T10:19:37.070273 7882 ] Object file /opt/ccache/e/6/6655b110377c5794ea3d42e5b03bfa-1233342.o not in cache
[2017-10-06T10:19:37.074816 7882 ] Running real compiler
[2017-10-06T10:19:37.074831 7882 ] Executing /usr/bin/clang++ -g -pipe -fcolor-diagnostics -c -o main.o main.cpp
[2017-10-06T10:19:37.398610 7882 ] Unlink /opt/ccache/e/6/6655b110377c5794ea3d42e5b03bfa-1233342.o.tmp.stdout.mac-01.7882.ofhqvE
[2017-10-06T10:19:37.400198 7882 ] Unlink /opt/ccache/e/6/6655b110377c5794ea3d42e5b03bfa-1233342.o.tmp.stderr.mac-01.7882.39oFr2
[2017-10-06T10:19:37.403101 7882 ] Copying main.o to /opt/ccache/e/6/6655b110377c5794ea3d42e5b03bfa-1233342.o via /opt/ccache/e/6/6655b110377c5794ea3d42e5b03bfa-1233342.o.mac-01.7882.EgzGp8 (uncompressed)
[2017-10-06T10:19:37.408524 7882 ] Stored in cache: main.o -> /opt/ccache/e/6/6655b110377c5794ea3d42e5b03bfa-1233342.o
[2017-10-06T10:19:37.419266 7882 ] Added object file hash to /opt/ccache/5/5/f68a8996015d5eea1dfae7c20049e9-262.manifest
[2017-10-06T10:19:37.421525 7882 ] Acquired lock /opt/ccache/e/stats.lock
[2017-10-06T10:19:37.427699 7882 ] Releasing lock /opt/ccache/e/stats.lock
[2017-10-06T10:19:37.427711 7882 ] Unlink /opt/ccache/e/stats.lock
[2017-10-06T10:19:37.428801 7882 ] Result: cache miss
```

And after second build (another machine):
```
$ ccache -s
cache directory                     /opt/ccache
primary config                      /opt/ccache/ccache.conf
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             2
cache hit rate                      0.00 %
cleanups performed                     0
files in cache                         4
cache size                         176.1 kB
max cache size                      10.0 GB
```
Log:
```
[2017-10-06T10:26:52.641543 13220] === CCACHE 3.3.4 STARTED =========================================
[2017-10-06T10:26:52.641543 13220] Config: (environment) base_dir = /Users/sebpot/test
[2017-10-06T10:26:52.641543 13220] Config: (environment) cache_dir = /opt/ccache
[2017-10-06T10:26:52.641543 13220] Config: (default) cache_dir_levels = 2
[2017-10-06T10:26:52.641543 13220] Config: (default) compiler =
[2017-10-06T10:26:52.641543 13220] Config: (default) compiler_check = mtime
[2017-10-06T10:26:52.641543 13220] Config: (default) compression = false
[2017-10-06T10:26:52.641543 13220] Config: (default) compression_level = 6
[2017-10-06T10:26:52.641543 13220] Config: (default) cpp_extension =
[2017-10-06T10:26:52.641543 13220] Config: (default) direct_mode = true
[2017-10-06T10:26:52.641543 13220] Config: (default) disable = false
[2017-10-06T10:26:52.641543 13220] Config: (default) extra_files_to_hash =
[2017-10-06T10:26:52.641543 13220] Config: (environment) hard_link = false
[2017-10-06T10:26:52.641543 13220] Config: (environment) hash_dir = false
[2017-10-06T10:26:52.641543 13220] Config: (default) ignore_headers_in_manifest =
[2017-10-06T10:26:52.641543 13220] Config: (default) keep_comments_cpp = false
[2017-10-06T10:26:52.641543 13220] Config: (default) limit_multiple = 0.8
[2017-10-06T10:26:52.641543 13220] Config: (environment) log_file = cache.log
[2017-10-06T10:26:52.641543 13220] Config: (default) max_files = 0
[2017-10-06T10:26:52.641543 13220] Config: (environment) max_size = 10.0G
[2017-10-06T10:26:52.641543 13220] Config: (default) path =
[2017-10-06T10:26:52.641543 13220] Config: (default) prefix_command =
[2017-10-06T10:26:52.641543 13220] Config: (default) prefix_command_cpp =
[2017-10-06T10:26:52.641543 13220] Config: (default) read_only = false
[2017-10-06T10:26:52.641543 13220] Config: (default) read_only_direct = false
[2017-10-06T10:26:52.641543 13220] Config: (default) recache = false
[2017-10-06T10:26:52.641543 13220] Config: (default) run_second_cpp = true
[2017-10-06T10:26:52.641543 13220] Config: (environment) sloppiness = file_macro, include_file_mtime, include_file_ctime, time_macros, pch_defines
[2017-10-06T10:26:52.641543 13220] Config: (default) stats = true
[2017-10-06T10:26:52.641543 13220] Config: (environment) temporary_dir = /tmp/ccache_test
[2017-10-06T10:26:52.641543 13220] Config: (default) umask =
[2017-10-06T10:26:52.641543 13220] Config: (default) unify = false
[2017-10-06T10:26:52.642192 13220] Command line: ccache clang++ -g -pipe -o main.o -c main.cpp
[2017-10-06T10:26:52.642209 13220] Hostname: mac-02
[2017-10-06T10:26:52.642556 13220] Working directory: /Users/sebpot/test
[2017-10-06T10:26:52.642609 13220] Automatically enabling colors
[2017-10-06T10:26:52.642618 13220] Source file: main.cpp
[2017-10-06T10:26:52.642622 13220] Object file: main.o
[2017-10-06T10:26:52.642635 13220] Trying direct lookup
[2017-10-06T10:26:52.642683 13220] Looking for object file hash in /opt/ccache/5/a/5205b905474fce9f337f345ddd6dcc-262.manifest
[2017-10-06T10:26:52.644494 13220] No such manifest file
[2017-10-06T10:26:52.644504 13220] Did not find object file hash in manifest
[2017-10-06T10:26:52.645421 13220] Running preprocessor
[2017-10-06T10:26:52.645430 13220] Executing /usr/bin/clang++ -pipe -g -fcolor-diagnostics -E main.cpp
[2017-10-06T10:26:52.727020 13220] Got object file hash from preprocessor
[2017-10-06T10:26:52.729127 13220] Object file /opt/ccache/a/1/e38a1dae08d57bd284ae24d420caf5-1233342.o not in cache
[2017-10-06T10:26:52.732935 13220] Running real compiler
[2017-10-06T10:26:52.732945 13220] Executing /usr/bin/clang++ -pipe -g -fcolor-diagnostics -c -o main.o main.cpp
[2017-10-06T10:26:52.967373 13220] Unlink /opt/ccache/a/1/e38a1dae08d57bd284ae24d420caf5-1233342.o.tmp.stdout.mac-02.13220.rVK06P
[2017-10-06T10:26:52.968803 13220] Unlink /opt/ccache/a/1/e38a1dae08d57bd284ae24d420caf5-1233342.o.tmp.stderr.mac-02.13220.GVA1Dq
[2017-10-06T10:26:52.971507 13220] Copying main.o to /opt/ccache/a/1/e38a1dae08d57bd284ae24d420caf5-1233342.o via /opt/ccache/a/1/e38a1dae08d57bd284ae24d420caf5-1233342.o.mac-02.13220.7S3Ubg (uncompressed)
[2017-10-06T10:26:52.976363 13220] Stored in cache: main.o -> /opt/ccache/a/1/e38a1dae08d57bd284ae24d420caf5-1233342.o
[2017-10-06T10:26:52.984787 13220] Added object file hash to /opt/ccache/5/a/5205b905474fce9f337f345ddd6dcc-262.manifest
[2017-10-06T10:26:52.986829 13220] Acquired lock /opt/ccache/a/stats.lock
[2017-10-06T10:26:52.991545 13220] Releasing lock /opt/ccache/a/stats.lock
[2017-10-06T10:26:52.991554 13220] Unlink /opt/ccache/a/stats.lock
[2017-10-06T10:26:52.992420 13220] Result: cache miss
```

**Comment by mikhirev** [comment] 2017-10-06 09:42
@sebpot Are you using clang of exactly the same version on both machines?

**Comment by sebpot** [comment] 2017-10-06 10:11
@mikhirev: yes

Machine 1:
```bash
$ clang++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Machine 2:
```bash
$ clang++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Also just got cache hit for the case above (with one file) for such configuration:
```
hash_dir = false
log_file = /tmp/ccache_test.log
max_size = 10.0G
sloppiness = file_macro,include_file_ctime,include_file_mtime,time_macros
temporary_dir = /tmp/ccache_test
unify = true
```
And `CCACHE_DIR` set to NFS share, and `CCACHE_BASEDIR` set to code directory (`pwd`).

**Comment by afbjorklund** [comment] 2017-10-07 10:56
What we talked about last time, was to offer better debugging possibilites for hash contents.
i.e. the simplest way to be able to debug these issues is to add a watcher to `hash_buffer`

**Comment by afbjorklund** [comment] 2017-10-07 14:50
Currently you need to set both -DCCACHE_DEBUG_HASH when compiling,
and $CCACHE_DEBUG_HASH when running. See 0eec63e2 and 93c6e9ac

**Comment by sebpot** [comment] 2017-10-12 07:27
@afbjorklund: The debug hash output file differs between first and following compilations, even on the same machine with local ccache. It's also huge (over 100k lines) in my case. There are some common parts, but due to the differences between these files I am not able to determine the cause of the problem.

**Comment by jrosdahl** [comment] 2018-01-11 15:49
> It's also huge (over 100k lines) in my case. There are some common parts, but due to the differences between these files I am not able to determine the cause of the problem.

It's often useful to check where the two files start to differ. Would it be possible for you to publish the two debug hash output files somewhere?

**Comment by KholdStare** [comment] 2018-04-11 22:32
@sebpot Any update on this?

**Comment by megatesla** [comment] 2018-05-10 00:10
I'm looking into using ccache on AFS. Not quite the same as NFS, but I imagine I'll bump into this problem or others like it. Currently I'm getting fails from the built-in tests for the CCACHE_NOHASHDIR and fdebug-prefix-map testcases. I'll dig into these a bit and see if they're similar to what @sebpot is seeing, or if they should be different issues.

**Comment by jrosdahl** [comment] 2018-10-17 18:32
Note: In ccache 3.5 there is now an improved way of debugging cache misses: https://ccache.samba.org/manual/latest.html#_cache_debugging

**Comment by jrosdahl** [comment] 2018-12-03 21:47
Closing this due to timeout. Please comment if you have new findings.

**Closed by jrosdahl** 2018-12-03 21:47 UTC
Labels: support

**Comment by chri7325** [comment] 2019-09-17 00:14
I just retried this workflow on the latest ccache and I'm also hitting the same issue. MacOS works fine when using local cache but will fail when using an NFS location set with ccache_dir. The ccache stats get randomly wiped when multiple instances of ccache are running at the same time. The log files output from CCACHE_DEBUG just mention that there are cache misses. I also occasionally see `ccache internal error                  1` but it goes away almost immediately as the stats get cleared again.

**Comment by jrosdahl** [comment] 2019-09-17 19:41
> The ccache stats get randomly wiped when multiple instances of ccache are running at the same time.

That could indicate bad NFS configuration or bad NFS implementation. See also #124 and especially https://github.com/ccache/ccache/issues/124#issuecomment-242168307 with the following comments. Perhaps you would like to try the mentioned lockfile-stress-test program on your system?

**Comment by chri7325** [comment] 2019-09-17 20:29
@jrosdahl I think you're correct. Running the program gives me a lot of issues with locks. I'll see if our IST department can take a look at our NFS shares. Thanks!
