### ISSUE TITLE
Support different flag for response files

### ISSUE THREAD

**Issue by janhieber** [ccache/ccache#1136] opened 2022-08-16 08:52 UTC
On Windows the command line might be to long and the default behavior of ninja/compilers is to use response files.

CCache supports response files with the @file syntax. Would it be possible to make this flag configurable? For example, Tasking compiler uses -f file instead @file.

Thanks!

**Comment by jrosdahl** [comment] 2022-08-18 17:57
Hi,

It sounds like you're asking for support of the TriCore Tasking compiler? See #842.

I don't want to add special configuration for how to interpret a specific flag.

**Comment by janhieber** [comment] 2022-08-19 07:44
Ahh yes, ideed. I tried in Linux with something like that:
```bash
#!/usr/bin/env sh
set -eu
set -- $(echo "$@" | sed -r -e 's/@/-f /')
eval wine ${TASKING_PATH}/ctc/bin/cctc.exe "$@"
```

And I had the impression that it works. Also in Windows it seems to work as long as the response file is not needed.

On Windows a wrapper was not possible because CCache did not want to execute my `.bat`.  
And when I used something like `CCACHE_PREFIX=C:\system32\cmd.exe /C` it always complained that it cannot find `cmd.exe`...

But as I see a PR is on the way and I'm very happy to see it! Thanks very much for all the work you put in!

**Comment by jrosdahl** [comment] 2022-08-20 11:45
OK, thanks. I'll mark this as a duplicate.

**Comment by jrosdahl** [comment] 2022-08-20 11:45
Duplicate of #841

**Closed by jrosdahl** 2022-08-20 11:45 UTC
Labels: feature

**Comment by vsplesk** [comment] 2022-09-05 07:50
Sorry, NO, please reopen. This issue is NOT Tasking specific, it is Windows specific. And yes, the Tasking mod author had to modify your core option handling because your core option handling hardcodes GCC-specific behavior (@ prefix)

But to me that looks wrong. There are other also compiles that use alternative prefixes for the same purpose (arm with the --via option, for example), see https://developer.trustedfirmware.org/T95 for example or https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/925 in particular. So even cmake authors had to make this customizable long time ago but the very same problem propagates to other compiler wrappers like ccache because they might prolong the object file paths and therefore suddenly hit the Windows limit.

**Comment by jrosdahl** [comment] 2022-09-09 08:23
> This issue is NOT Tasking specific, it is Windows specific.

I don't quite understand what you mean. A compiler doesn't magically learn how to use e.g. `-f` to refer to a response file just because it's running on Windows, so you must mean something else, but what?

> your core option handling hardcodes GCC-specific behavior (@ prefix) But to me that looks wrong. 

When you say that it looks _wrong_ it seems to me that you're implying that ccache is supposed to support any compiler. But that is simply not the case. Ccache currently supports "GCC-like" compilers, "MSVC-like" compilers and [some others](https://ccache.dev/platform-compiler-language-support.html). Ccache only understands `@` for response files since that's what the set of currently supported compilers use.

If we in the future add support for more compilers, like Tasking Tricore or some compiler that uses `--via`, then of course code needs to be written to support those compilers including how they use response files. But making the flag _configurable_, as suggested in https://github.com/ccache/ccache/issues/1136#issue-1340024864, is not the right way forward.
