### ISSUE TITLE
`-DSTATIC_LINK=ON` leads to "`-lgcc_s` not found" on POSIX systems

### ISSUE THREAD

**Issue by Flamefire** [ccache/ccache#1330] opened 2023-09-04 12:32 UTC
### How to reproduce ###

1. Configure on Linux with `-DSTATIC_LINK=ON`
2. Build

### Actual behavior ###
```
[105/106] Linking CXX executable ccache
FAILED: ccache 
: && /beegfs/ws/1/s3248973-EasyBuild/easybuild-ml/software/GCCcore/12.3.0/bin/g++ -O3 -DNDEBUG -flto=auto -fno-fat-lto-objects -fuse-ld=bfd CMakeFiles/ccache.dir/src/main.cpp.o -o ccache  src/libccache_framework.a  -Wl,-Bdynamic  /beegfs/ws/1/s3248973-EasyBuild/easybuild-ml/software/zstd/1.5.5-GCCcore-12.3.0/lib/libzstd.a  -Wl,-Bstatic  -pthread  src/third_party/libthird_party.a  src/third_party/blake3/libblake3.a  -Wl,-Bdynamic  /beegfs/ws/1/s3248973-EasyBuild/easybuild-ml/software/hiredis/1.2.0-GCCcore-12.3.0/lib/libhiredis.a  -Wl,-Bstatic && :
/beegfs/ws/1/s3248973-EasyBuild/easybuild-ml/software/binutils/2.40-GCCcore-12.3.0/bin/ld.bfd: cannot find -lgcc_s: Datei oder Verzeichnis nicht gefunden
/beegfs/ws/1/s3248973-EasyBuild/easybuild-ml/software/binutils/2.40-GCCcore-12.3.0/bin/ld.bfd: /beegfs/ws/1/s3248973-EasyBuild/easybuild-ml/software/hiredis/1.2.0-GCCcore-12.3.0/lib/libhiredis.a(net.c.o): in function `_redisContextConnectTcp':
net.c:(.text+0x10a8): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/beegfs/ws/1/s3248973-EasyBuild/easybuild-ml/software/binutils/2.40-GCCcore-12.3.0/bin/ld.bfd: cannot find -lgcc_s: Datei oder Verzeichnis nicht gefunden
collect2: Fehler: ld gab 1 als Ende-Status zurck
[106/106] Linking CXX executable unittest/unittest
FAILED: unittest/unittest 
: && /beegfs/ws/1/s3248973-EasyBuild/easybuild-ml/software/GCCcore/12.3.0/bin/g++ -O3 -DNDEBUG -flto=auto -fno-fat-lto-objects -fuse-ld=bfd unittest/CMakeFiles/unittest.dir/TestUtil.cpp.o unittest/CMakeFiles/unittest.dir/main.cpp.o unittest/CMakeFiles/unittest.dir/test_Args.cpp.o unittest/CMakeFiles/unittest.dir/test_AtomicFile.cpp.o unittest/CMakeFiles/unittest.dir/test_Config.cpp.o unittest/CMakeFiles/unittest.dir/test_Depfile.cpp.o unittest/CMakeFiles/unittest.dir/test_Hash.cpp.o unittest/CMakeFiles/unittest.dir/test_Stat.cpp.o unittest/CMakeFiles/unittest.dir/test_Util.cpp.o unittest/CMakeFiles/unittest.dir/test_argprocessing.cpp.o unittest/CMakeFiles/unittest.dir/test_ccache.cpp.o unittest/CMakeFiles/unittest.dir/test_compopt.cpp.o unittest/CMakeFiles/unittest.dir/test_compression_types.cpp.o unittest/CMakeFiles/unittest.dir/test_core_MsvcShowIncludesOutput.cpp.o unittest/CMakeFiles/unittest.dir/test_core_Statistics.cpp.o unittest/CMakeFiles/unittest.dir/test_core_StatisticsCounters.cpp.o unittest/CMakeFiles/unittest.dir/test_core_StatsLog.cpp.o unittest/CMakeFiles/unittest.dir/test_hashutil.cpp.o unittest/CMakeFiles/unittest.dir/test_storage_local_StatsFile.cpp.o unittest/CMakeFiles/unittest.dir/test_storage_local_util.cpp.o unittest/CMakeFiles/unittest.dir/test_util_BitSet.cpp.o unittest/CMakeFiles/unittest.dir/test_util_Bytes.cpp.o unittest/CMakeFiles/unittest.dir/test_util_Duration.cpp.o unittest/CMakeFiles/unittest.dir/test_util_LockFile.cpp.o unittest/CMakeFiles/unittest.dir/test_util_TextTable.cpp.o unittest/CMakeFiles/unittest.dir/test_util_TimePoint.cpp.o unittest/CMakeFiles/unittest.dir/test_util_Tokenizer.cpp.o unittest/CMakeFiles/unittest.dir/test_util_XXH3_128.cpp.o unittest/CMakeFiles/unittest.dir/test_util_XXH3_64.cpp.o unittest/CMakeFiles/unittest.dir/test_util_expected.cpp.o unittest/CMakeFiles/unittest.dir/test_util_file.cpp.o unittest/CMakeFiles/unittest.dir/test_util_path.cpp.o unittest/CMakeFiles/unittest.dir/test_util_string.cpp.o unittest/CMakeFiles/unittest.dir/test_util_zstd.cpp.o unittest/CMakeFiles/unittest.dir/test_InodeCache.cpp.o -o unittest/unittest  src/libccache_framework.a  src/third_party/libthird_party.a  src/third_party/blake3/libblake3.a  -Wl,-Bdynamic  /beegfs/ws/1/s3248973-EasyBuild/easybuild-ml/software/zstd/1.5.5-GCCcore-12.3.0/lib/libzstd.a  -Wl,-Bstatic  -pthread  -Wl,-Bdynamic  /beegfs/ws/1/s3248973-EasyBuild/easybuild-ml/software/hiredis/1.2.0-GCCcore-12.3.0/lib/libhiredis.a  -Wl,-Bstatic && :
/beegfs/ws/1/s3248973-EasyBuild/easybuild-ml/software/binutils/2.40-GCCcore-12.3.0/bin/ld.bfd: cannot find -lgcc_s
```

### Expected behavior ###
 Build works.

### Environment ###
4.8.3

We currently (since a long time) work around this by using `'-DCMAKE_EXE_LINKER_FLAGS="-static" -DZSTD_LIBRARY="$EBROOTZSTD/lib/libzstd.a" -DHIREDIS_LIBRARY="$EBROOTHIREDIS/lib/libhiredis.a"` but would love to use the simpler `STATIC_LINK` option

**Comment by jrosdahl** [comment] 2023-09-16 18:53
Some background: The STATIC_LINK build option was added in #1058 to address problems with prebuilt Windows executables. I'm not sure whether POSIX/Linux was intended to work with STATIC_LINK. But in any case, `STATIC_LINK=ON` is now suggested in [the installation instructions](https://github.com/ccache/ccache/blob/master/doc/INSTALL.md) as a generic switch to enable static linking, so I agree something should be fixed, either the implementation or documentation.

If we aim to fix the implementation, I'm not sure if it's a good idea to just use `-static` since static linking with glibc is ["highly discouraged"](https://stackoverflow.com/questions/57476533/why-is-statically-linking-glibc-discouraged). The original installation instructions just mentioned how to link zstd and hiredis statically (just like you already do).

@rkitover: What do you think?

**Comment by rkitover** [comment] 2023-09-16 20:53
I'll take a look. I did intend this to be a generic option, but I did not test on Linux at the time.

**Comment by rkitover** [comment] 2023-09-16 21:17
Yeah this is going to take some work, I'll get back to you in a few days hopefully.

**Comment by rkitover** [comment] 2023-09-16 23:17
Let's think about what we want to do here exactly.

Actual statically linked binaries on Linux are a rare use-case, for example busybox, fsck and similar tools for catastrophic recovery. I don't see a use-case for ccache being an actual statically linked binary, so it would be reasonable for this option to mean "link all libraries statically except libc." It is practically impossible for the resulting binary being used with different libc versions to cause any issues.

According to the thread jrosdahl linked about actual static linking on Linux, it's bad if services like iconv are used, do we use anything like that? If not, we could make an actual static binary, however I would still prefer the former option, unless there is any reason to do so.

As far as the implementation goes, do we want the option to cause a build failure if only a dynamic library is available for something and make the static linking a hard requirement? Or throw a loud warning?

I think it would be reasonable to build static zstd and hiredis if this option is on and only dynamic versions are available on the system. In this case if the corresponding `FROM_INTERNET` options are explicitly set to `OFF` it would be a build failure, but we already made them default to `ON`. This will take some work but is totally doable.

**Comment by Flamefire** [comment] 2023-09-17 08:49
As a datapoint: We use EasyBuild to install modules (i.e. software and some files setting env variables to make it "available") on HPC systems. We have multiple toolchains (GCC versions and libraries build with it) and may want to use ccache. But for that we need to make sure there are no dynamic dependencies of ccache as otherwise another module (e.g. zstd) would be required. That in turn could clash with the module to be build which may use a different compiler or e.g. another zstd version.

To make ccache fully self-contained we also use `-static` and [a check](https://github.com/easybuilders/easybuild-easyconfigs/blob/ac9184078f6d3ebc9e9fde7565d44842b4873f96/easybuild/easyconfigs/c/ccache/ccache-4.8.3.eb#L51) that the ccache binary is indeed not dynamically linked.

**Comment by jrosdahl** [comment] 2023-09-17 11:11
Another datapoint: I build the Linux x86_64 binary release on CentOS 7 with CMake options `-DCMAKE_BUILD_TYPE=Release -DHIREDIS_FROM_INTERNET=ON -DZSTD_FROM_INTERNET=ON -DCMAKE_EXE_LINKER_FLAGS_INIT=-static-libstdc++` to get it "statically linked enough".

**Comment by rkitover** [comment] 2023-09-17 13:12
@Flamefire would it be sufficient for your purposes then if this option were to make an executable that **ONLY** depends on libc and no other dynamic libraries?

**Comment by Flamefire** [comment] 2023-09-18 07:55
> @Flamefire would it be sufficient for your purposes then if this option were to make an executable that **ONLY** depends on libc and no other dynamic libraries?

It would be better, but we still need `-DCMAKE_EXE_LINKER_FLAGS="-static"` as otherwise running `ccache` compiled with a recent compiler (loaded via modules during build)  results in 
```
/tmp/ebinstall/bin/ccache: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/ebinstall/bin/ccache)
/tmp/ebinstall/bin/ccache: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/ebinstall/bin/ccache)
/tmp/ebinstall/bin/ccache: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/ebinstall/bin/ccache)
```

So we do need to link that std-libs statically.   
But we can do with that flag as we have others already in place.

Speaking of flags: Currently we use `-DZSTD_FROM_INTERNET=OFF -DHIREDIS_FROM_INTERNET=OFF` so that it doesn't even try downloading files from the internet as that would circumvent e.g. the checksum checks of software (sources) we compile and doesn't work in offline environments. A unified flag `CCACHE_NO_DOWNLOAD` or something similar to the "standard CMake" `FETCHCONTENT_FULLY_DISCONNECTED` to disable ALL downloads (including possible future additions) would be nice.

**Comment by rkitover** [comment] 2023-09-18 17:07
@Flamefire that is `libstdc++` not `libc`, can you please try `-DCMAKE_EXE_LINKER_FLAGS_INIT=-static-libstdc++` like jrosdahl does along with your method for static zstd and hiredis and let me know if that works for you?

**Closed** 2023-10-29 08:28 UTC
Labels: bug, help wanted, build
