### ISSUE TITLE
ccache issue with base_dir option (version 3.7.5, Windows 10, MinGW)

### ISSUE THREAD

**Issue by Shionigami** [ccache/ccache#559] opened 2020-03-09 14:09 UTC
Hello.

I got problems with the base_dir option which does not seems to work well:
- When using the command:
   `ccache -o base_dir=<project_folder>`
- The file ccache.conf contains only the max_size by default (running on Windows Prompt)

- The environment variable CCACHE_BASEDIR seems to be taken in account when I run tests, but, the conversion from absolute to relative path seems to not work. I already tried with both forward and backslashes, but I got different results:
  - Forward slashes: I got errors due to the path length, like when I do not define any base_dir
  - Back slashes: When I check the log, there are only the 4 first chars which are removed. Looks like it is running this part: // Strip \\?\ from the file name.
-> We run it on minGW

For info, we are using ccache 3.7.5 for GHS compatibility.

Thanks.

**Comment by Shionigami** [comment] 2020-03-10 10:08
Here are some additional information:
Config:
- max_size = 2G
- compression = true
- depend_mode = true
As base_dir configuration is not working with the command ccache -o base_dir=, I set it up with the environment variable.

The path used for the GHS commands are formatted with forward slashes, like:
 -ID:/Project/Folder1/file.c

**Comment by Shionigami** [comment] 2020-04-01 08:13
I finally have time to focus on that issue.
I found that, if I use the option base_dir or cache_dir_levels, ccache is not able to configure it:
```
ccache -o cache_dir_levels=2
return false
ccache: error: cache directory levels must be between 1 and 8
```
```
ccache -o base_dir=c:\temp
  -> No error, but no new entry in the config file
```
In the code, I found in the file confitems_lookup.c, that both options are using the macro ITEM_V(), which is not working.
To make sure that the problem comes from there, I replaced ITEM_V() with ITEM() and did a test, added some print messages to check if ccache is able to execute the whole code.

With ITEM_V(), in the function conf_set_value_in_file(), ccache crashes with base_dir with the following test:
`	char dummy[8] = {0}; // The maximum entry size in struct conf.
	if (!item->parser(value, (void *)dummy, errmsg)
	    || (item->verifier && !item->verifier(value, errmsg))) {
        printf("\nreturn false\n");
		return false;
	}`
With cache_dir_levels, it returns a failure.

If I use ITEM() instead of ITEM_V(), it is able to print all the debug messages I added.

I will now start to investigate on the other issue I got with base_dir, which does not seem to be able to make relative path from the absolute path. Then, I cannot share the cache between different projects.

**Comment by AlexanderLanin** [comment] 2020-04-04 20:43
@Shionigami: I guess there is a typo in your version info? confitems_lookup.c and ITEM_V were gone way before 3.7.5?

Can you try with a recent version like [3.7.9](https://github.com/ccache/ccache/releases/tag/v3.7.9)?

**Comment by Shionigami** [comment] 2020-04-06 14:44
Here is the code comming from 3.7.5:
`#define ITEM_ENTRY(name, type, verify_fn) \
	offsetof(struct conf, name), confitem_parse_ ## type, \
	confitem_format_ ## type, verify_fn
#define ITEM(name, type) \
	ITEM_ENTRY(name, type, NULL)
#define ITEM_V(name, type, verification) \
	ITEM_ENTRY(name, type, confitem_verify_ ## verification)
struct conf_item;`

With this, it is not working, and same with v3.7.9.

I tried with the other version of ccache available on my machine, and with 3.3.4, I am able to add a base_dir to the configuration file, using a command like:
ccache -o base_dir=c:\tmp

With none of the later version it is working.

**Comment by AlexanderLanin** [comment] 2020-04-06 17:46
So far I can confirm a bug in setting base_dir and cache_dir_levels in v3.7.9 in linux. Working on a fix.
C is not helping since there is no proper type checking :-(

Working on a fix.

**Comment by AlexanderLanin** [comment] 2020-04-06 18:12
I'm guessing the linked PR will resolve this only partially. But maybe you could retest so we have a clear picture of the state now?

**Comment by Shionigami** [comment] 2020-04-07 08:00
I tested your fix and it works =)
Thanks!

The other thing I am trying to fix is sharing the cache, especially when I am building from different location.
I already made a lot of local changes to fix some of the issues, mostly due to / and \. But still, it is not working.

I will try to make some tests with a small Linux project, and try to analyze the differences in the log.

**Comment by jrosdahl** [comment] 2020-08-26 18:27
@Shionigami: Do you want more input or can we close this issue?

**Closed** 2020-09-25 18:48 UTC
Labels: awaiting feedback, bug, help wanted, windows
