### ISSUE TITLE
Ignore --start/end-no-unused-arguments

### ISSUE THREAD

**Issue by nolange** [ccache/ccache#1328] opened 2023-08-28 09:41 UTC
### Description ###
Clang 14 starts supporting `--{start,end}-no-unused-arguments`. Those are merely options for compiler(-argument) diagnostics and don't affect the generated code/binary in any way. Would be nice to passed those down but wont affect the hash code.

[Blog Post](https://maskray.me/blog/2023-08-25-clang-wunused-command-line-argument)

**Comment by jrosdahl** [comment] 2023-08-28 17:07
Thanks for the suggestion!

I can see why you would want that behavior, but ccache doesn't only cache and reproduce the object file but also warning messages. In other words, if your idea is implemented it would mean that

```
clang -c example.c -la                                    # prints unused argument warning
clang -c example.c --start-no-unused-arguments -la        # does not print unused argument warning
```

and

```
ccache clang -c example.c -la                             # prints unused argument warning
ccache clang -c example.c --start-no-unused-arguments -la # prints unused argument warning
```

no longer would behave the same, which would not be good.

**Comment by nolange** [comment] 2023-08-28 20:53
The warnings are purely command line though, don't depend at all on the content of the file (only name I believe).

I get your point, ignoring won't cut it.

Skipping the argument for the preprocessor hash could help? That way you would run the preprocessor with the options, which should generate the warnings, while still ending up with the same output.

**Comment by nolange** [comment] 2023-09-02 21:16
> > Skipping the argument for the preprocessor hash could help? That way you would run the preprocessor with the options, which should generate the warnings, while still ending up with the same output.
> 
> You're talking about a solution, but I don't understand what problem the solution aims to solve. What do you want to accomplish?

Better hit-rate. I just found out about these flags, would be nice if ccache would still use the identical binary output.

**Comment by jrosdahl** [comment] 2023-09-14 19:52
> Skipping the argument for the preprocessor hash could help? That way you would run the preprocessor with the options, which should generate the warnings, while still ending up with the same output.

That would not be enough since there can be warnings emitted when compiling but not when preprocessing.

So, I don't think the result of  `ccache clang A B` be reused by `ccache clang A --start-no-unused-arguments B` since the first command can produce stderr output that the second command doesn't. When ccache runs the second command, it can't know whether the first command produced stderr just by inspecting the second command line or its preprocessor output. Similarly, a previous result of  `ccache clang A --start-no-unused-arguments B` can't be reused by `ccache clang A B`.

One thing that _could_ be done is to add a [sloppiness](https://ccache.dev/manual/4.8.3.html#config_sloppiness) setting that lets you say that you don't care about missing or extraneous warnings, and then ccache could strip `--start-no-unused-arguments` and `--end-no-unused-arguments` before running the compiler. However, I don't see much value in such a setting since it feels unlikely that a user has many compiler invocations that only differ in whether `--start-no-unused-arguments` and `--end-no-unused-arguments` are present. Thus, I don't quite see why there is a real problem to solve in the first place.

Do you have any other suggestions? Otherwise I think we can close this issue.

**Closed** 2023-09-15 09:24 UTC
Labels: improvement, compiler: clang
