### ISSUE TITLE
backslashes in rsp files are parsed incorecctly 

### ISSUE THREAD

**Issue by hebran42** [ccache/ccache#1327] opened 2023-08-25 15:17 UTC
### How to reproduce ###

1. Use small "hello world" source file: hello.c
2. Enable ccache logfile
3. Create a rsp file `c:\path\to\test.rsp` with following content: `/c /Fo"dir1\dir2\\" "C:\path\to\hello.c"`
4. `mkdir dir1 && mkdir dir1\dir2`
5. Run `ccache "c:\Program Files\Path\to\cl.exe" @c:\path\to\test.rsp`

### Actual behavior ###

In ccache log file you will find an entry: `[2023-08-25T16:17:58.529939 24636] No input file found`
ccache can not find an input file.

### Expected behavior ###

I expected to find a log line like: `[2023-08-25T16:19:09.783988 32492] Source file: C:/path/to/hello.c`
If you run `ccache "c:\Program Files\Path\to\cl.exe" /c /Fo"dir1\dir2\\" "C:\path\to\hello.c` everything works
as expected and ccache can find the source file.
The bug seems related to the double backslash in /Fo parameter value. If you leave out the double backslash in the rsp file, ccache will find the source file.
Unfortunately this syntax with doube backslash at the end is what Microsoft recommends: https://learn.microsoft.com/en-us/cpp/build/reference/fo-object-file-name?view=msvc-170#example
And it is also what CMake produce in its VS generator.

### Environment ###

ccache version 8..4.2
Visual Studio 2022 Version 17.4.2
CMake 3.27.2

**Comment by jrosdahl** [comment] 2023-08-26 14:27
Thanks for the bug report. This was fixed by #1303 (not yet part of a released ccache version).

Duplicate of #1247

**Closed by jrosdahl** 2023-08-26 14:27 UTC
Labels: bug
