### ISSUE TITLE
Compile error with latest Visual Studio 2022 update

### ISSUE THREAD

**Issue by rkitover** [ccache/ccache#1076] opened 2022-05-18 21:30 UTC
Once I installed the latest Visual Studio 2022 update, I am getting the following compile error when building. I don't know enough about C++ to know what this means exactly:

```console
[1/103] Building CXX object src\CMakeF...cache_framework.dir\AtomicFile.cpp.obj
FAILED: src/CMakeFiles/ccache_framework.dir/AtomicFile.cpp.obj
C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1432~1.313\bin\Hostx64\x64\cl.exe  /nologo /TP -DHAVE_REDIS_STORAGE_BACKEND -DSTATIC_GETOPT -DWIN32_LEAN_AND_MEAN -DXXH_STATIC_LINKING_ONLY -Dnssv_CONFIG_SELECT_STRING_VIEW=nssv_STRING_VIEW_NONSTD -IC:\Users\rkitover\source\repos\ccache\build-msvc -IC:\Users\rkitover\source\repos\ccache\src -IC:\Users\rkitover\source\repos\ccache\build-msvc\zstd-1.5.2\lib -IC:\Users\rkitover\source\repos\ccache\build-msvc\hiredis-1.0.2\include /DWIN32 /D_WINDOWS  /GR /EHsc /MD /O2 /Ob2 /DNDEBUG /FIC:/Users/rkitover/source/repos/ccache/build-msvc/config.h /Zc:preprocessor /Zc:__cplusplus /D_CRT_SECURE_NO_WARNINGS /WX /W4 /wd5105 /wd4244 /wd4245 /wd4267 /wd4706 /wd4996 -std:c++17 /showIncludes /Fosrc\CMakeFiles\ccache_framework.dir\AtomicFile.cpp.obj /Fdsrc\CMakeFiles\ccache_framework.dir\ccache_framework.pdb /FS -c C:\Users\rkitover\source\repos\ccache\src\AtomicFile.cpp
C:\Users\rkitover\source\repos\ccache\src\core/exceptions.hpp(57): error C2664: 'std::string fmt::v8::format<>(fmt::v8::basic_format_string<char>)': cannot convert argument 1 from 'core::Error' to 'fmt::v8::basic_format_string<char>'
C:\Users\rkitover\source\repos\ccache\src\core/exceptions.hpp(57): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\rkitover\source\repos\ccache\src\third_party/fmt/core.h(3117): note: see declaration of 'fmt::v8::format'
C:\Users\rkitover\source\repos\ccache\src\AtomicFile.cpp(48): note: see reference to function template instantiation 'core::Error::Error<core::Error&>(core::Error &)' being compiled
C:\Users\rkitover\source\repos\ccache\src\core/exceptions.hpp(57): error C2280: 'core::ErrorBase::ErrorBase(void)': attempting to reference a deleted function
C:\Users\rkitover\source\repos\ccache\src\core/exceptions.hpp(36): note: compiler has generated 'core::ErrorBase::ErrorBase' here
C:\Users\rkitover\source\repos\ccache\src\core/exceptions.hpp(36): note: 'core::ErrorBase::ErrorBase(void)': function was implicitly deleted because a base class 'std::runtime_error' has either no appropriate default constructor or overload resolution was ambiguous
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\stdexcept(101): note: see declaration of 'std::runtime_error'
ninja: build stopped: subcommand failed.
```

With Visual Studio 2019 this error does not occur.

**Comment by cristianadam** [comment] 2022-05-20 08:01
I would assume it has to do with the `fmt` library.

**Comment by Predelnik** [comment] 2022-05-28 12:21
So this seems to be just msvc's bug/regression, I reduced and reported it here:
https://developercommunity.visualstudio.com/t/Throwing-class-instance-with-non-default/10056237?entry=problem

Workaround as I see currently involves explicitly `=delete`ing ctor accepting lvalue references for example adding `ErrorBase(ErrorBase&) = delete;` within `ErrorBase` seems to fix it. Not sure if it should be committed or not, it's ugly but it's only a single line at least.

**Comment by rkitover** [comment] 2022-05-28 13:51
@Predelnik

Thank you for figuring this out and submitting it upstream! I've been trying to learn C++ better the last few years but to be honest I don't really understand this.

@jrosdahl 

Would you like me to open and verify a PR with his fix? (I will set him as author.)

Also, would you like me to open a PR to update the CI config to add a VS2022 runner? I also wanted to add msbuild as well as Ninja runners since that was an issue in the last thing we did.

**Comment by jrosdahl** [comment] 2022-06-07 09:02
@rkitover wrote: 
> Would you like me to open and verify a PR with his fix? (I will set him as author.)

I don't know what to do about this.

> Also, would you like me to open a PR to update the CI config to add a VS2022 runner? I also wanted to add msbuild as well as Ninja runners since that was an issue in the last thing we did.

That would be OK by me if that helps somebody.

That said, and just to be clear: I have no personal goal to work on supporting building ccache with MSVC since I don't see any immediate benefit. (It's rather the opposite: to me it's more of a burden to handle portability issues.)

**Comment by rkitover** [comment] 2022-06-07 10:07
> > Also, would you like me to open a PR to update the CI config to add a VS2022 runner? I also wanted to add msbuild as well as Ninja runners since that was an issue in the last thing we did.
> 
> That would be OK by me if that helps somebody.

I will wait until this particular issue is resolved, since we don't want every PR failing CI.

> That said, and just to be clear: I have no personal goal to work on supporting building ccache with MSVC since I don't see any immediate benefit. (It's rather the opposite: to me it's more of a burden to handle portability issues.)

I'm sorry for dragging you into this, as this issue among others shows the portability burden is heavier than I expected. But given that this is a C++ project that uses cmake, someone would have done it eventually anyway.

I was hoping VS support would attract more devs, to improve Windows support and the whole project. I haven't really been following the project so I don't know if this has happened to any extent, but devs of any sort are always in short supply.

I will try to help with build issues related to this and other things.

In this particular issue, I don't understand the C++ involved, but I will do some research.

**Comment by jrosdahl** [comment] 2022-06-07 10:34
> I will wait until this particular issue is resolved, since we don't want every PR failing CI.

OK.

> I was hoping VS support would attract more devs, to improve Windows support and the whole project.

I understand, and I agree that it's good to make it easier for Windows developers to contribute.

> I haven't really been following the project so I don't know if this has happened to any extent, but devs of any sort are always in short supply.

There are a couple of other people who contribute Windows/MSVC stuff, but I'm not sure what development environment they use.

Sorry if I sound a bit negative from time to time – I appreciate the effort and help from everybody! It's just that keeping up with the increased scope of what ccache can do and where it is supposed to work kind of swamps my spare time, so I seldom have time to work on things I would like to.

> I will try to help with build issues related to this and other things.

Thanks.

**Closed** 2022-06-11 17:42 UTC
Labels: help wanted, portability, build, compiler: msvc
