### ISSUE TITLE
test.debug_prefix_map now failing for Fedora rawhide on i686/x86_64 and aarch64

### ISSUE THREAD

**Issue by opoplawski** [ccache/ccache#919] opened 2021-08-24 03:57 UTC
### How to reproduce ###
Building the ccache package on Fedora rawhide

### Actual behavior ###
```
 3/43 Test  #8: test.debug_prefix_map ............***Failed    0.28 sec
Compiler:         gcc (/usr/bin/gcc)
Compiler version: gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
CUDA compiler:    not available
Running test suite debug_prefix_map.
FAILED
Test suite:     debug_prefix_map (line 33)
Test case:      Mapping of debug info CWD
Failure reason: File test.o contains "/builddir/build/BUILD/ccache-4.4/redhat-linux-build/testdir/2559617/run/dir1"
Actual statistics counters
==========================
autoconf_test                    0
bad_compiler_arguments           0
bad_output_file                  0
cache_miss                       1
cache_size_kibibyte              8
called_for_link                  0
called_for_preprocessing         0
cleanups_performed               0
compile_failed                   0
compiler_check_failed            0
compiler_produced_empty_output   0
compiler_produced_no_output      0
compiler_produced_stdout         0
could_not_find_compiler          0
could_not_use_modules            0
could_not_use_precompiled_header 0
direct_cache_hit                 0
direct_cache_miss                1
error_hashing_extra_file         0
files_in_cache                   2
internal_error                   0
missing_cache_file               0
multiple_source_files            0
no_input_file                    0
output_to_stdout                 0
preprocessed_cache_hit           0
preprocessed_cache_miss          1
preprocessor_error               0
primary_storage_hit              0
primary_storage_miss             2
recache                          0
secondary_storage_error          0
secondary_storage_hit            0
secondary_storage_miss           0
secondary_storage_timeout        0
unsupported_code_directive       0
unsupported_compiler_option      0
unsupported_source_language      0
```

### Environment ###
ccache version 4.2.1 and 4.4

Fedora's CI seems to indicate that this may have been triggered by either an llvm or binutils update.  Not sure why llvm/clang would have affected the gcc build tests though.  

https://koschei.fedoraproject.org/package/ccache?collection=f35

binutils changes:
```
 Fri Aug 20 2021 Nick Clifton  <nickc@redhat.com> - 2.37-9
- Fix a few testsuite failures.
- Backport upstream patch to fix fd exhaustion
- Resolves: https://sourceware.org/bugzilla/show_bug.cgi?id=28138

* Tue Aug 10 2021 Nick Clifton  <nickc@redhat.com> - 2.37-5
- Fix a local change to readelf which resulted in a success exit code for non-existant files.  (#1990817)

* Mon Aug 09 2021 Nick Clifton  <nickc@redhat.com> - 2.37-4
- Ensure that dir[0] contains pwd in gas generated DWARF-5 directory tables.  (#1966987)
```
Tests still succeed on armv7hl, ppc64le, and s390x.

**Comment by opoplawski** [comment] 2021-08-24 03:59
Possibly more constraint on what changes triggered it in the F34 differences: https://koschei.fedoraproject.org/package/ccache?collection=f34

**Comment by jrosdahl** [comment] 2021-08-24 19:34
Thanks for the bug report.

I can reproduce the problem in Fedora 34 with binutils-2.35.2-5.fc34.x86_64.rpm but not with binutils-2.35.1-41.fc34.x86_64.rpm. It seems to be the _"Ensure that dir[0] contains pwd in gas generated DWARF-5 directory tables.  (\#1966987)"_ part of the binutils upgrade that triggers the failure. I guess it has been backported to binutils-2.35.2-5?

The ccache test case in question wants to verify that `-fdebug-prefix-map=$(pwd)=something_relative` indeed rewrites all matching debug paths (when the compiler is executed via ccache) in the object file. Since object files as of binutils 2.35.2-5 apparently always include the absolute path to CWD this assumption breaks.

This is unfortunately not only a test problem but a problem of correctness of object files produced by ccache. Since object files compiled with `-g` include CWD, ccache normally has to include CWD in the input hash by default to avoid false positive cache hits, which makes it impossible to share cache hits between directories. However, with `-fdebug-prefix-map=$(pwd)=something_relative` ccache assumes that it's OK not to include CWD in the hash since the paths have been normalized. This is documented here: https://ccache.dev/manual/4.4.html#config_hash_dir

@opoplawski: Are you familiar with the background of this change? The changelog message doesn't give any motivation it seems. Is it intentional that the new entry is not affected by `-fdebug-prefix-map`?

I don't know very much about these things, but I note that [commit 3417bfca676ff0b440f070a09837813e99b2c731 in binutils](https://sourceware.org/git/?p=binutils-gdb.git;a=blobdiff;f=gas/dwarf2dbg.c;h=8f5248534ad68019dee87d230a33589d5ce917eb;hp=460daaa5c0c38bf02e7e093def81ae19d09fe3d5;hb=3417bfca676ff0b440f070a09837813e99b2c731;hpb=b18bfc0946d2cfba76c0a56852bcf1c7a42f4868) says

```
/* In DWARF-5 the 0 entry in the directory table is expected to be
   the same as the DW_AT_comp_dir (which is set to the current build
   directory).  Since we are about to create a directory entry that
   is not the same, allocate the current directory first.
```

but since `DW_AT_comp_dir` *is* affected by `-fdebug-prefix-map` AFAIK.

**Comment by opoplawski** [comment] 2021-08-24 19:37
I'm afraid I know nothing about the binutils change, just passing it along.  I think you'll need to working it out with the binutils folks directly.

**Comment by jrosdahl** [comment] 2021-08-28 12:24
Reported to the binutils bug tracker: https://sourceware.org/bugzilla/show_bug.cgi?id=28266

**Comment by jrosdahl** [comment] 2021-09-11 07:37
Fixed on binutils-gdb master: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=58f3b6a3495074da39ba6e19935e4401dcbacf88

**Closed** 2021-09-11 07:38 UTC
Labels: bug, closed: invalid
