### ISSUE TITLE
Unable to build webkit-gtk on Gentoo (pre-build, unable to find pthread.h)

### ISSUE THREAD

**Issue by fluffynuts** [ccache/ccache#787] opened 2021-01-21 06:33 UTC
### How to reproduce ###

1. `FEATURES="ccache" emerge -1 =net-libs/webkit-gtk-2.30.3`

### Actual behavior ###
Pre-build check fails: unable to locate pthread.h

### Expected behavior ###
Should build fine - running `FEATURES="-ccache" emerge -1 =net-libs/webkit-gtk-2.30.3` continues to the compile phase

### Environment ###

ccache version 4.1
OS: Gentoo

build log and ccache logs
[build.log](https://github.com/ccache/ccache/files/5847316/build.log)
[webkit-gtk-ccache.log](https://github.com/ccache/ccache/files/5847317/webkit-gtk-ccache.log)

Please let me know if I can furnish further information

**Comment by jrosdahl** [comment] 2021-01-23 17:58
Hi,

build.log says _"ccache: error: Failed to write to /tmp/webkit-gtk-ccache.log: Permission denied"_, so isn't this the same issue as #767?

**Comment by fluffynuts** [comment] 2021-01-24 06:16
O, sorry, that was me trying to get a log file just from one build. The failure happened without the log file, so I'll try again. If I enable CCACHE_DEBUG, where should I look for information to add here?

**Comment by fluffynuts** [comment] 2021-01-24 06:31
Remembering that portage switches out users during different phases, I created the log file manually first and made it world-writable, so here's the updates if they're of any use:

[build.log](https://github.com/ccache/ccache/files/5861661/build.log)
[webkit-gtk-ccache.log](https://github.com/ccache/ccache/files/5861660/webkit-gtk-ccache.log)

reading the man page for ccache, it seems that CCACHE_DEBUG will create files alongside object files as it tries to build / resolve. Now it looks like the issue happens at the config phase, so (a) will there be the artifacts you're looking for and (b) what should I look for in my 50+gig cache area?

**Comment by jrosdahl** [comment] 2021-01-25 06:21
Right, CMake removes the files produced by `CCACHE_DEBUG` when it cleans up its temporary directories. You can pass `--debug-trycompile` to `cmake` to tell it not to.

Debug information is however likely not of much use unless you know which command CMake actually runs (and which source code) to probe for pthread.h. Have a look in `CMakeFiles/CMakeError.log` and `CMakeFiles/CMakeOutput.log` to find out what CMake does to probe for `pthread.h`. Then you can compare the behavior (using `<object-file>.ccache-log` and `<object-file>.ccache-input-text`) of that command with and without ccache. On cache hits, you can also check the contents of a manifest file using `ccache --dump-manifest <path>`.

I can't think of more tips than this given the available information. I don't run Gentoo myself so I'll have a hard time reproducing the problem using only the hint `FEATURES="ccache" emerge -1 =net-libs/webkit-gtk-2.30.3`.

**Comment by fluffynuts** [comment] 2021-01-26 20:04
ok, so this looks interesting (from CMakeError.log):

```
Determining if the include file pthread.h exists failed with the following output:
Change Dir: /var/tmp/portage/net-libs/webkit-gtk-2.30.3/work/webkit-gtk-2.30.3_build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja cmTC_d5382 && [1/2] Building C object CMakeFiles/cmTC_d5382.dir/CheckIncludeFile.c.o
[2/2] Linking C executable cmTC_d5382
FAILED: cmTC_d5382 
: && /usr/lib/ccache/bin/x86_64-pc-linux-gnu-gcc -fcolor-diagnostics -Wextra -Wall -Wno-expansion-to-defined -Wno-psabi -Wno-maybe-uninitialized -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -march=native -O2 -fno-strict-aliasing -fno-exceptions  -Wl,-O1 -Wl,--as-needed -Wl,--no-keep-memory -fuse-ld=gold -Wl,--disable-new-dtags CMakeFiles/cmTC_d5382.dir/CheckIncludeFile.c.o  -o cmTC_d5382   && :
x86_64-pc-linux-gnu-gcc: error: unrecognized command line option ‘-fcolor-diagnostics’
ninja: build stopped: subcommand failed.
```

as I understand it, `x86_64-pc-linux-gnu-gcc` passes `-f` flags to the underlying compiler and gcc's man page has the option `-fdiagnostics-color`, not `-fcolor-diagnostics`. If I modify the commandline above to use `-fdiagnostics-color`, then the command runs without the `unrecognises command line option` error, but fails for me because I'm missing the temp file the CMake has apparently made. Does this help?

**Comment by fluffynuts** [comment] 2021-01-26 20:07
to track down more info, I'm def gonna need guidance, so I'm open for suggestions.

**Comment by jrosdahl** [comment] 2021-01-27 17:39
That is most likely bug #740. The fix will be included in ccache 4.2 which I intend to release quite soon, hopefully later this week.

**Comment by jrosdahl** [comment] 2021-01-30 12:44
Duplicate of #740.

**Closed by jrosdahl** 2021-01-30 12:44 UTC
Labels: bug

**Comment by mcatanzaro** [comment] 2021-02-04 20:05
Definitely #740, glad to see it's already fixed.

Source: two hours of my life I won't get back. :P
