### ISSUE TITLE
clang compilation database support (different ways) 

### ISSUE THREAD

**Issue by piratk** [ccache/ccache#1248] opened 2023-02-06 10:11 UTC
Clang has the support to generate "compilation database" in different ways.

Either using "bear" tool, or using flags, either on command line or from environment

It would be nice if these compilation database files could be generated at the same time as using ccache. 

Additional information can be found here:
https://clang.llvm.org/docs/JSONCompilationDatabase.html

**Comment by piratk** [comment] 2023-02-06 10:23
I see this is partially/mostly related to or a copy of pull request [277](https://github.com/ccache/ccache/pull/277)

**Comment by jrosdahl** [comment] 2023-02-06 20:14
Thanks for the suggestion. Yes, this sounds like a duplicate of #446. I'll update its title to make it easier to find.

Duplicate of #446

**Closed** 2023-02-06 20:14 UTC
Labels: feature
